#!/usr/bin/env python3
"""Convert a port/ref/tools/mkgecko.py-format reference script into the
port's own `--play` format (port/src/pad/pad_play.c).

Why this exists: the reference rig's input scripts are compiled into Dolphin
Gecko codes that patch the game's private `_PadBtn`/`_PadDStk` globals
directly, by fixed memory address, at the VI hook (see mkgecko.py's own
docstring). That mechanism does not exist outside Dolphin. The port's `PADRead`
seam has no addresses at all -- a script feeds raw controller state into
`PADRead`, and the game's own `PadADConv`/repeat logic in src/game/pad.c does
the rest, per port/ref/notes.md §6.3 ("a replay layer must feed HuPadRead raw
state ... not synthesise BtnDown itself").

The two directive vocabularies were deliberately kept close, so this is a
straight, checked transcription rather than a reinterpretation:

  mkgecko.py "at <frame> <frames> BTN[,BTN..]"       -> unchanged (buttons are
  mkgecko.py "at <frame> <frames> dstk:<DIR>[,<DIR>]"   the same PAD_BUTTON_*
                                                          names; dstk: is
                                                          native to pad_play.c
                                                          too, resolved there
                                                          to a raw stick push
                                                          rather than a
                                                          synthesised _PadDStk)
  mkgecko.py "mark <frame> <label>"                  -> unchanged

The one thing this script actually *does*, beyond copying: it validates every
button/direction name against the set pad_play.c understands, so a typo is
caught here instead of silently doing nothing at runtime, and it drops
mkgecko.py's Gecko/address framing (there is none to carry over).

Usage:  gecko2play.py script.txt out.play
"""
import argparse
import sys

BUTTONS = {"A", "B", "X", "Y", "Z", "L", "R", "START"}
DIRECTIONS = {"UP", "DOWN", "LEFT", "RIGHT"}


def convert(path):
    out_lines = []
    n_at = n_mark = 0
    with open(path) as f:
        for lineno, raw in enumerate(f, 1):
            s = raw.split("#", 1)[0].strip()
            if not s:
                continue
            p = s.split()
            if p[0].lower() == "mark":
                if len(p) < 3:
                    sys.exit(f"{path}:{lineno}: bad mark line: {raw!r}")
                frame, label = p[1], " ".join(p[2:])
                out_lines.append(f"mark {frame} {label}")
                n_mark += 1
                continue
            if p[0].lower() != "at":
                sys.exit(f"{path}:{lineno}: unknown directive {p[0]!r}")
            if len(p) != 4:
                sys.exit(f"{path}:{lineno}: 'at' takes 3 arguments: {raw!r}")
            _, frame, frames, what = p
            for tok in what.split(","):
                if tok.lower().startswith("dstk:"):
                    dirs = tok.split(":", 1)[1].split(",")
                    for d in dirs:
                        if d.upper() not in DIRECTIONS:
                            sys.exit(f"{path}:{lineno}: unknown direction {d!r} in {tok!r}")
                elif tok.upper() not in BUTTONS:
                    sys.exit(f"{path}:{lineno}: unknown button {tok!r}")
            out_lines.append(f"at {frame} {frames} {what}")
            n_at += 1
    return out_lines, n_at, n_mark


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("script", help="a port/ref/tools/mkgecko.py-format reference script")
    ap.add_argument("out", help="output .play file, in pad_play.c's format")
    a = ap.parse_args()

    lines, n_at, n_mark = convert(a.script)
    with open(a.out, "w") as f:
        f.write("# Generated by port/tools/gecko2play.py -- do not edit by hand.\n")
        f.write(f"# Source: {a.script}\n")
        f.write("# Frame numbers are the port's VIGetRetraceCount(), which tracks the\n")
        f.write("# game's own GlobalCounter frame-for-frame (see pad_play.c's header).\n")
        f.write("\n".join(lines) + "\n")
    print(f"{a.out}: {n_at} 'at' directives, {n_mark} marks")


if __name__ == "__main__":
    main()
