#!/usr/bin/env python3
"""M43 (PLAN.md 58.2): the rename list for the render thread's instance of the
translation (src/gx/gx_rti.h).  Reads `nm -g` of the game thread's objects of
the four files on stdin and writes one `#define NAME rti_NAME` per global they
define, except the SHARED ones: facts about the one GL context (its limits,
its extension entry points, the white texture's name) that both instances
read and neither owns."""
import sys, re
SHARED = {"glc_white_name_shared", "gx_vp_limits", "gx_vp_env_bulk", "gx_vp_last_vbo_unused"}
names = set()
for line in sys.stdin:
    f = line.split()
    if len(f) == 3 and f[1] not in ("U", "u"):
        n = f[2]
        if n.startswith("_"):
            n = n[1:]
        if n in SHARED or not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", n):
            continue
        names.add(n)
print("/* generated by tools/gen_rti_names.py -- do not edit */")
for n in sorted(names):
    print("#define %s rti_%s" % (n, n))
