#!/usr/bin/env python3
"""Work out what goes into each of the 99 relocatable modules, and write it
out as a makefile fragment.

The port turns every REL into one native Mach-O bundle (`port/docs/PLAN.md`
§2.4b), so it needs, per module, the exact list of translation units the
console's REL linker put in it.  That list is not guesswork: the decomp's own
`config/GMPE01_00/rels/<mod>/splits.txt` names every source file in the
module, and `config/GMPE01_01/config.yml` names every module.  Reading those
two means the port can never drift from the decomp -- if an upstream commit
splits a new file into a module, the port picks it up on the next build.

Six modules (`m300Dll`, `m302Dll`, `m303Dll`, `m330Dll`, `m333Dll`,
`msetupDll`) are 144-byte placeholder RELs on the disc with no code at all,
only empty `.ctors`/`.dtors`.  They get a generated one-line module whose
`_prolog` returns 0, so the loader's bookkeeping stays uniform across all 99.

    gen_rels.py --out build-host/rels.mk [--list]
"""
import argparse
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))

MODULE_RE = re.compile(
    r"^- object: files/dll/(?P<name>\S+)\.rel\n"
    r"(?:.*\n)*?"
    r"\s+splits: (?P<splits>\S+)\n",
    re.M)
FILE_RE = re.compile(r"^(\S+):$", re.M)


def modules():
    """[(name, [src/... paths])] in config.yml order."""
    cfg = open(os.path.join(ROOT, "config/GMPE01_01/config.yml")).read()
    out = []
    for m in MODULE_RE.finditer(cfg):
        splits = open(os.path.join(ROOT, m.group("splits"))).read()
        srcs = ["src/" + f for f in FILE_RE.findall(splits) if f != "Sections"]
        for s in srcs:
            if not os.path.exists(os.path.join(ROOT, s)):
                raise SystemExit("gen_rels: %s: %s does not exist" % (m.group("name"), s))
        srcs = with_executor(srcs)
        out.append((m.group("name"), srcs))
    return out


BOARD_CREATE_RE = re.compile(r"^void BoardCreate\b", re.M)
PROLOG_RE = re.compile(r"^s32 _prolog\b", re.M)


def with_executor(srcs):
    """Make sure the module has a `_prolog`/`_epilog`.

    18 of the 99 modules do not list `REL/executor.c` in their splits file.
    Three of them (`mentDll`, `mstory4Dll`, `safDll`) wrote the entry thunk out
    into their own source instead; the other 15 have it inside the module's own
    `.text` range where it was never split out, though on the console it was
    the same 0xA0 bytes of `executor.c` all the same.  Give the second group
    the shared one -- the board modules get `board_executor.c`, whose
    `ObjectSetup` registers `BoardCreate` / `BoardDestroy` instead of being the
    module's own.
    """
    if any(s.endswith("/executor.c") or s.endswith("/board_executor.c") for s in srcs):
        return srcs
    if not srcs:
        return srcs
    bodies = [open(os.path.join(ROOT, s)).read() for s in srcs]
    if any(PROLOG_RE.search(b) for b in bodies):
        return srcs
    board = any(BOARD_CREATE_RE.search(b) for b in bodies)
    ex = "src/REL/board_executor.c" if board else "src/REL/executor.c"
    return [ex] + srcs


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out")
    ap.add_argument("--list", action="store_true")
    args = ap.parse_args()

    mods = modules()
    if args.list:
        for name, srcs in mods:
            print("%-16s %2d  %s" % (name, len(srcs), " ".join(srcs) or "(placeholder)"))
        print("%d modules, %d distinct sources"
              % (len(mods), len({s for _, ss in mods for s in ss})))
    if not args.out:
        return

    lines = ["# GENERATED by port/tools/gen_rels.py -- do not edit.",
             "REL_MODULES := " + " ".join(n for n, _ in mods), ""]
    for name, srcs in mods:
        lines.append("REL_SRCS_%s := %s" % (name, " ".join(srcs)))
    lines.append("")
    # A fixed load address per module (PLAN.md 24.2).  dyld places a bundle
    # wherever it likes unless the bundle asks, and "wherever it likes" depends
    # on everything else the process has mapped -- so the same module came back
    # 340 KB lower in a run that loaded it at a different point, and a snapshot
    # taken in one run could not be restored in the other: the game keeps
    # pointers into module text and holds the dlopen handle itself.  Each
    # module is therefore linked at its own slot, a megabyte apart (the largest
    # bundle is 160 KB), in a window nothing else uses.  It also makes a
    # backtrace address mean the same thing in every run, which gdb likes.
    lines.append("# fixed -seg1addr per module: see port/tools/gen_rels.py")
    for i, (name, _srcs) in enumerate(mods):
        lines.append("REL_SEG1_%s := 0x%08x" % (name, 0x30000000 + i * 0x00100000))
    lines.append("")
    os.makedirs(os.path.dirname(os.path.abspath(args.out)) or ".", exist_ok=True)
    text = "\n".join(lines)
    old = open(args.out).read() if os.path.exists(args.out) else None
    if old != text:
        with open(args.out, "w") as f:
            f.write(text)


if __name__ == "__main__":
    main()
