#!/usr/bin/env python3
"""M32: the PortOptions field list for --defaults (src/platform/defaults.c).

Reads `typedef struct PortOptions { ... } PortOptions;` out of include/port.h
and writes src/platform/opt_fields.h, one OPT_*(name) line per scalar or
string member, so the effective-options print names every option without a
hand-kept table.  Run it when a field is added:

    python3 port/tools/gen_optfields.py
"""
import os, re, sys
here = os.path.dirname(os.path.abspath(__file__))
port = os.path.dirname(here)
src = open(os.path.join(port, 'include/port.h')).read()
m = re.search(r'typedef struct PortOptions \{(.*?)\n\} PortOptions;', src, re.S)
if not m:
    sys.exit('no PortOptions in port.h')
body = re.sub(r'/\*.*?\*/', '', m.group(1), flags=re.S)
kinds = {'int': 'OPT_INT', 'unsigned': 'OPT_UNS', 'long long': 'OPT_LL',
         'double': 'OPT_DBL', 'const char*': 'OPT_STR'}
out = ['/* generated by tools/gen_optfields.py from include/port.h -- do not edit */']
n = 0
for decl in body.split(';'):
    decl = ' '.join(decl.split())
    if not decl:
        continue
    mm = re.match(r'(const char\s*\*|long long|unsigned|int|double)\s*(\w+)$', decl.replace('* ', '*'))
    if not mm:
        mm = re.match(r'(const char)\s*\*\s*(\w+)$', decl)
        if not mm:
            sys.stderr.write('skipped: %s\n' % decl)
            continue
        kind, name = 'const char*', mm.group(2)
    else:
        kind, name = mm.group(1).replace(' *', '*').replace('char *', 'char*'), mm.group(2)
    out.append('%s(%s)' % (kinds[kind], name))
    n += 1
open(os.path.join(port, 'src/platform/opt_fields.h'), 'w').write('\n'.join(out) + '\n')
print('%d fields' % n)
