#!/usr/bin/env python3
"""Regenerate `src/game/kerent.c`'s trampoline table as portable assembly.

`kerent.c` is 4,089 lines of which 2,047 are one Metrowerks `asm` function,
`_kerent`, holding 1,019 pairs of

    entry _kerjmp_OSReport
    b OSReport

-- the DOL's export thunks.  On the console a REL that imported `OSReport`
was relocated against `_kerjmp_OSReport` rather than against `OSReport`
itself, so the whole DOL export surface was reachable through one contiguous
table of branches and the REL linker only ever had to relocate against
labels it could find in the DOL's symbol table.

The port's mirror drops the function, because it drops every top-level
definition containing Metrowerks assembly (PLAN.md §9.4), and the M1 link did
not miss it: with one Mach-O bundle per REL, dyld binds a module's imports
straight to the real symbols in the main binary and no thunk table is
involved.  It is regenerated anyway, for three reasons: `_kerent` is in
config.yml's `force_active` list and is therefore part of what the DOL *is*;
the table is the authoritative statement of which 1,019 symbols the DOL
exports to modules, which is a useful cross-check on the generated export
list; and a later single-binary build mode (PLAN.md §2.4a) would need exactly
this table.

Each pair becomes, on both targets:

    .globl __kerjmp_OSReport
    __kerjmp_OSReport:
        b _OSReport

which assembles identically for arm64 and for 32-bit PowerPC -- both spell an
unconditional tail branch `b`, and Mach-O spells a C symbol with a leading
underscore, so `_kerjmp_X` in C is `__kerjmp_X` in assembly.  Branch range is
not a concern: `b` reaches ±128 MB on arm64 and ±32 MB on PowerPC against a
binary of about one.

    gen_kerent.py --out build-host/kerent_tramp.s --version 1 [--list]
"""
import argparse
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
KERENT = os.path.join(ROOT, "src/game/kerent.c")

# The Metrowerks EABI register save/restore helpers.  They exist in the DOL
# because the Metrowerks runtime emitted them, they have no equivalent in a
# GCC/clang build, and no REL ever imports one through the table -- a module
# that needed them had its own copy.  Six entries, skipped.
SKIP = {"_savegpr_14", "_savegpr_15", "_savegpr_16",
        "_restgpr_14", "_restgpr_15", "_restgpr_16"}

ENTRY_RE = re.compile(r"^\s*entry\s+(_kerjmp_\S+)\s*$")
BRANCH_RE = re.compile(r"^\s*b\s+(\S+)\s*$")
IF_RE = re.compile(r"^\s*#if\s+(.*)$")
ELSE_RE = re.compile(r"^\s*#else\s*$")
ENDIF_RE = re.compile(r"^\s*#endif\s*$")


def pairs(version):
    """[(thunk, target)] for the version being built.

    `VERSION_PAL` / `VERSION_NTSC` guard a handful of entries; VERSION=1 is
    GMPE01_01, USA Rev 1, so NTSC is true and PAL is false.
    """
    names = {"VERSION_PAL": version == 2, "VERSION_NTSC": version in (0, 1)}
    out = []
    stack = []  # each element: is this branch live?
    pending = None
    started = False
    for line in open(KERENT):
        if not started:
            if line.startswith("asm void _kerent"):
                started = True
            continue
        m = IF_RE.match(line)
        if m:
            cond = m.group(1).strip()
            stack.append(names.get(cond, cond not in names and None))
            continue
        if ELSE_RE.match(line):
            if stack:
                stack[-1] = not stack[-1]
            continue
        if ENDIF_RE.match(line):
            if stack:
                stack.pop()
            continue
        live = all(bool(s) for s in stack)
        m = ENTRY_RE.match(line)
        if m:
            pending = m.group(1) if live else None
            continue
        m = BRANCH_RE.match(line)
        if m and pending:
            if m.group(1) not in SKIP:
                out.append((pending, m.group(1)))
            pending = None
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out")
    ap.add_argument("--version", type=int, default=1)
    ap.add_argument("--list", action="store_true")
    args = ap.parse_args()

    ps = pairs(args.version)
    if args.list:
        for thunk, target in ps:
            print("%s -> %s" % (thunk, target))
        print("%d trampolines" % len(ps))
    if not args.out:
        return

    lines = [
        "/* GENERATED by port/tools/gen_kerent.py from src/game/kerent.c -- do not edit.",
        " *",
        " * %d export thunks, the DOL's own `_kerent` table.  See the generator's" % len(ps),
        " * docstring for why the port keeps them even though dyld binds each REL",
        " * bundle's imports straight to the real symbols.",
        " */",
        "\t.text",
        "\t.align 2",
        "\t.globl __kerent",
        "__kerent:",
    ]
    for thunk, target in ps:
        lines.append("\t.globl _%s" % thunk)
        lines.append("_%s:" % thunk)
        lines.append("\tb _%s" % target)
    lines.append("")
    text = "\n".join(lines)
    os.makedirs(os.path.dirname(os.path.abspath(args.out)) or ".", exist_ok=True)
    old = open(args.out).read() if os.path.exists(args.out) else None
    if old != text:
        with open(args.out, "w") as f:
            f.write(text)


if __name__ == "__main__":
    main()
