#!/usr/bin/env python3
"""Write the soak's input script: board-start.play's metronome, without an end.

    port/tools/mksoakplay.py [frames] > soak.play

`port/ref/movies/board-start.play` is a metronome -- START through the boot,
then A for four frames out of every sixty-four -- that stops at frame 29,960
because that is as far as the walk it was captured for went.  A soak has no
end, so it needs the same shape and more of it, and 62,000 `at` lines is not
something to keep in the repository when four lines of Python will emit them.

With `--com4` no screen needs a *specific* button: instDll dismisses its own
instruction screen when all four players are CPU (src/REL/instDll/main.c:294),
which is the one press board-start.play had to place by hand (PLAN.md 15.3).
So the metronome alone walks every menu, every results screen and every board
restart.  There are deliberately no STARTs after the boot: a START on the
board opens the pause menu, and the walk never comes back.
"""
import sys

end = int(sys.argv[1]) if len(sys.argv) > 1 else 4000000

print("# soak.play -- generated by port/tools/mksoakplay.py; see its docstring.")
for f in range(700, 1150, 50):
    print("at %d 6 START" % f)
for f in range(1160, end, 64):
    print("at %d 4 A" % f)
