/* GENERATED by port/tools/gen_kerent.py from src/game/kerent.c -- do not edit.
 *
 * 1011 export thunks, the DOL's own `_kerent` table.  See the generator's
 * docstring for why the port keeps them even though dyld binds each REL
 * bundle's imports straight to the real symbols.
 */
	.text
	.align 2
	.globl __kerent
__kerent:
	.globl __kerjmp_OSDumpStopwatch
__kerjmp_OSDumpStopwatch:
	b _OSDumpStopwatch
	.globl __kerjmp_PSVECDotProduct
__kerjmp_PSVECDotProduct:
	b _PSVECDotProduct
	.globl __kerjmp_PSVECDistance
__kerjmp_PSVECDistance:
	b _PSVECDistance
	.globl __kerjmp_PSVECSquareDistance
__kerjmp_PSVECSquareDistance:
	b _PSVECSquareDistance
	.globl __kerjmp_VIGetDTVStatus
__kerjmp_VIGetDTVStatus:
	b _VIGetDTVStatus
	.globl __kerjmp_OSGetProgressiveMode
__kerjmp_OSGetProgressiveMode:
	b _OSGetProgressiveMode
	.globl __kerjmp_OSSetProgressiveMode
__kerjmp_OSSetProgressiveMode:
	b _OSSetProgressiveMode
	.globl __kerjmp_PSVECSubtract
__kerjmp_PSVECSubtract:
	b _PSVECSubtract
	.globl __kerjmp_PSMTXTranspose
__kerjmp_PSMTXTranspose:
	b _PSMTXTranspose
	.globl __kerjmp_C_VECReflect
__kerjmp_C_VECReflect:
	b _C_VECReflect
	.globl __kerjmp_PSMTXInvXpose
__kerjmp_PSMTXInvXpose:
	b _PSMTXInvXpose
	.globl __kerjmp_PSMTXRotRad
__kerjmp_PSMTXRotRad:
	b _PSMTXRotRad
	.globl __kerjmp_PSMTXRotAxisRad
__kerjmp_PSMTXRotAxisRad:
	b _PSMTXRotAxisRad
	.globl __kerjmp_PSVECMag
__kerjmp_PSVECMag:
	b _PSVECMag
	.globl __kerjmp_PSVECScale
__kerjmp_PSVECScale:
	b _PSVECScale
	.globl __kerjmp_PSMTXMultVecSR
__kerjmp_PSMTXMultVecSR:
	b _PSMTXMultVecSR
	.globl __kerjmp_C_QUATRotAxisRad
__kerjmp_C_QUATRotAxisRad:
	b _C_QUATRotAxisRad
	.globl __kerjmp_C_QUATMtx
__kerjmp_C_QUATMtx:
	b _C_QUATMtx
	.globl __kerjmp_C_QUATAdd
__kerjmp_C_QUATAdd:
	b _C_QUATAdd
	.globl __kerjmp_C_QUATSlerp
__kerjmp_C_QUATSlerp:
	b _C_QUATSlerp
	.globl __kerjmp_PSQUATAdd
__kerjmp_PSQUATAdd:
	b _PSQUATAdd
	.globl __kerjmp_PSMTXQuat
__kerjmp_PSMTXQuat:
	b _PSMTXQuat
	.globl __kerjmp_PSQUATMultiply
__kerjmp_PSQUATMultiply:
	b _PSQUATMultiply
	.globl __kerjmp_PSQUATInverse
__kerjmp_PSQUATInverse:
	b _PSQUATInverse
	.globl __kerjmp_PSQUATNormalize
__kerjmp_PSQUATNormalize:
	b _PSQUATNormalize
	.globl __kerjmp_OSTicksToCalendarTime
__kerjmp_OSTicksToCalendarTime:
	b _OSTicksToCalendarTime
	.globl __kerjmp_GXWaitDrawDone
__kerjmp_GXWaitDrawDone:
	b _GXWaitDrawDone
	.globl __kerjmp_GXProject
__kerjmp_GXProject:
	b _GXProject
	.globl __kerjmp_GXGetProjectionv
__kerjmp_GXGetProjectionv:
	b _GXGetProjectionv
	.globl __kerjmp_GXGetViewportv
__kerjmp_GXGetViewportv:
	b _GXGetViewportv
	.globl __kerjmp_GXPixModeSync
__kerjmp_GXPixModeSync:
	b _GXPixModeSync
	.globl __kerjmp_GXSetIndTexOrder
__kerjmp_GXSetIndTexOrder:
	b _GXSetIndTexOrder
	.globl __kerjmp_GXSetIndTexMtx
__kerjmp_GXSetIndTexMtx:
	b _GXSetIndTexMtx
	.globl __kerjmp_GXSetTevIndWarp
__kerjmp_GXSetTevIndWarp:
	b _GXSetTevIndWarp
	.globl __kerjmp_GXSetTexCoordScaleManually
__kerjmp_GXSetTexCoordScaleManually:
	b _GXSetTexCoordScaleManually
	.globl __kerjmp_GXSetTevIndTile
__kerjmp_GXSetTevIndTile:
	b _GXSetTevIndTile
	.globl __kerjmp_GXNtsc480Prog
__kerjmp_GXNtsc480Prog:
	b _GXNtsc480Prog
	.globl __kerjmp_omSetStatBit
__kerjmp_omSetStatBit:
	b _omSetStatBit
	.globl __kerjmp_MGSeqDoneCheck
__kerjmp_MGSeqDoneCheck:
	b _MGSeqDoneCheck
	.globl __kerjmp_WipeStatGet
__kerjmp_WipeStatGet:
	b _WipeStatGet
	.globl __kerjmp_omMakeGroupEx
__kerjmp_omMakeGroupEx:
	b _omMakeGroupEx
	.globl __kerjmp_omGetGroupMemberListEx
__kerjmp_omGetGroupMemberListEx:
	b _omGetGroupMemberListEx
	.globl __kerjmp_MGSeqParamSet
__kerjmp_MGSeqParamSet:
	b _MGSeqParamSet
	.globl __kerjmp_MGSeqKill
__kerjmp_MGSeqKill:
	b _MGSeqKill
	.globl __kerjmp_ClusterAdjustObject
__kerjmp_ClusterAdjustObject:
	b _ClusterAdjustObject
	.globl __kerjmp_printWin
__kerjmp_printWin:
	b _printWin
	.globl __kerjmp_print8
__kerjmp_print8:
	b _print8
	.globl __kerjmp_HuSysVWaitSet
__kerjmp_HuSysVWaitSet:
	b _HuSysVWaitSet
	.globl __kerjmp_fn_800401D0
__kerjmp_fn_800401D0:
	b _fn_800401D0
	.globl __kerjmp_fn_800402FC
__kerjmp_fn_800402FC:
	b _fn_800402FC
	.globl __kerjmp_MGSeqInit
__kerjmp_MGSeqInit:
	b _MGSeqInit
	.globl __kerjmp_MGSeqCreate
__kerjmp_MGSeqCreate:
	b _MGSeqCreate
	.globl __kerjmp_omDelObjEx
__kerjmp_omDelObjEx:
	b _omDelObjEx
	.globl __kerjmp_MGSeqPosSet
__kerjmp_MGSeqPosSet:
	b _MGSeqPosSet
	.globl __kerjmp_atan2
__kerjmp_atan2:
	b _atan2
	.globl __kerjmp_atan2f
__kerjmp_atan2f:
	b _atan2f
	.globl __kerjmp_cos
__kerjmp_cos:
	b _cos
	.globl __kerjmp_MGSeqStatGet
__kerjmp_MGSeqStatGet:
	b _MGSeqStatGet
	.globl __kerjmp_Center
__kerjmp_Center:
	b _Center
	.globl __kerjmp_CRotM
__kerjmp_CRotM:
	b _CRotM
	.globl __kerjmp_CenterM
__kerjmp_CenterM:
	b _CenterM
	.globl __kerjmp_CZoomM
__kerjmp_CZoomM:
	b _CZoomM
	.globl __kerjmp_omOutViewMulti
__kerjmp_omOutViewMulti:
	b _omOutViewMulti
	.globl __kerjmp_omOutView
__kerjmp_omOutView:
	b _omOutView
	.globl __kerjmp_omAddObjEx
__kerjmp_omAddObjEx:
	b _omAddObjEx
	.globl __kerjmp_omInitObjMan
__kerjmp_omInitObjMan:
	b _omInitObjMan
	.globl __kerjmp_frandmod
__kerjmp_frandmod:
	b _frandmod
	.globl __kerjmp_fn_80040374
__kerjmp_fn_80040374:
	b _fn_80040374
	.globl __kerjmp_SetDefLight
__kerjmp_SetDefLight:
	b _SetDefLight
	.globl __kerjmp_HuSetVecF
__kerjmp_HuSetVecF:
	b _HuSetVecF
	.globl __kerjmp_HuSubVecF
__kerjmp_HuSubVecF:
	b _HuSubVecF
	.globl __kerjmp_frandf
__kerjmp_frandf:
	b _frandf
	.globl __kerjmp_MGSeqSprKill
__kerjmp_MGSeqSprKill:
	b _MGSeqSprKill
	.globl __kerjmp_mtxRotCat
__kerjmp_mtxRotCat:
	b _mtxRotCat
	.globl __kerjmp_Hu3DLayerHookSet
__kerjmp_Hu3DLayerHookSet:
	b _Hu3DLayerHookSet
	.globl __kerjmp_Hu3DNoSyncSet
__kerjmp_Hu3DNoSyncSet:
	b _Hu3DNoSyncSet
	.globl __kerjmp_Hu3DModelCreate
__kerjmp_Hu3DModelCreate:
	b _Hu3DModelCreate
	.globl __kerjmp_Hu3DModelLink
__kerjmp_Hu3DModelLink:
	b _Hu3DModelLink
	.globl __kerjmp_Hu3DHookFuncCreate
__kerjmp_Hu3DHookFuncCreate:
	b _Hu3DHookFuncCreate
	.globl __kerjmp_Hu3DModelPosSet
__kerjmp_Hu3DModelPosSet:
	b _Hu3DModelPosSet
	.globl __kerjmp_Hu3DModelPosSetV
__kerjmp_Hu3DModelPosSetV:
	b _Hu3DModelPosSetV
	.globl __kerjmp_Hu3DModelRotSet
__kerjmp_Hu3DModelRotSet:
	b _Hu3DModelRotSet
	.globl __kerjmp_Hu3DModelRotSetV
__kerjmp_Hu3DModelRotSetV:
	b _Hu3DModelRotSetV
	.globl __kerjmp_Hu3DModelScaleSet
__kerjmp_Hu3DModelScaleSet:
	b _Hu3DModelScaleSet
	.globl __kerjmp_Hu3DModelScaleSetV
__kerjmp_Hu3DModelScaleSetV:
	b _Hu3DModelScaleSetV
	.globl __kerjmp_Hu3DModelKill
__kerjmp_Hu3DModelKill:
	b _Hu3DModelKill
	.globl __kerjmp_Hu3DModelAllKill
__kerjmp_Hu3DModelAllKill:
	b _Hu3DModelAllKill
	.globl __kerjmp_Hu3DModelAttrSet
__kerjmp_Hu3DModelAttrSet:
	b _Hu3DModelAttrSet
	.globl __kerjmp_Hu3DModelAttrReset
__kerjmp_Hu3DModelAttrReset:
	b _Hu3DModelAttrReset
	.globl __kerjmp_Hu3DModelAttrGet
__kerjmp_Hu3DModelAttrGet:
	b _Hu3DModelAttrGet
	.globl __kerjmp_Hu3DModelMotionAttrGet
__kerjmp_Hu3DModelMotionAttrGet:
	b _Hu3DModelMotionAttrGet
	.globl __kerjmp_Hu3DBGColorSet
__kerjmp_Hu3DBGColorSet:
	b _Hu3DBGColorSet
	.globl __kerjmp_Hu3DModelCameraSet
__kerjmp_Hu3DModelCameraSet:
	b _Hu3DModelCameraSet
	.globl __kerjmp_Hu3DModelLayerSet
__kerjmp_Hu3DModelLayerSet:
	b _Hu3DModelLayerSet
	.globl __kerjmp_Hu3DModelTPLvlSet
__kerjmp_Hu3DModelTPLvlSet:
	b _Hu3DModelTPLvlSet
	.globl __kerjmp_Hu3DModelHookSet
__kerjmp_Hu3DModelHookSet:
	b _Hu3DModelHookSet
	.globl __kerjmp_Hu3DModelHookReset
__kerjmp_Hu3DModelHookReset:
	b _Hu3DModelHookReset
	.globl __kerjmp_Hu3DModelHookObjReset
__kerjmp_Hu3DModelHookObjReset:
	b _Hu3DModelHookObjReset
	.globl __kerjmp_Hu3DModelAmbSet
__kerjmp_Hu3DModelAmbSet:
	b _Hu3DModelAmbSet
	.globl __kerjmp_Hu3DModelShadowDispOn
__kerjmp_Hu3DModelShadowDispOn:
	b _Hu3DModelShadowDispOn
	.globl __kerjmp_Hu3DModelShadowDispOff
__kerjmp_Hu3DModelShadowDispOff:
	b _Hu3DModelShadowDispOff
	.globl __kerjmp_Hu3DModelProjectionSet
__kerjmp_Hu3DModelProjectionSet:
	b _Hu3DModelProjectionSet
	.globl __kerjmp_Hu3DModelProjectionReset
__kerjmp_Hu3DModelProjectionReset:
	b _Hu3DModelProjectionReset
	.globl __kerjmp_Hu3DModelObjPosGet
__kerjmp_Hu3DModelObjPosGet:
	b _Hu3DModelObjPosGet
	.globl __kerjmp_Hu3DModelObjMtxGet
__kerjmp_Hu3DModelObjMtxGet:
	b _Hu3DModelObjMtxGet
	.globl __kerjmp_Hu3DModelHiliteTypeSet
__kerjmp_Hu3DModelHiliteTypeSet:
	b _Hu3DModelHiliteTypeSet
	.globl __kerjmp_Hu3DModelReflectTypeSet
__kerjmp_Hu3DModelReflectTypeSet:
	b _Hu3DModelReflectTypeSet
	.globl __kerjmp_Hu3DModelHiliteMapSet
__kerjmp_Hu3DModelHiliteMapSet:
	b _Hu3DModelHiliteMapSet
	.globl __kerjmp_HuPadInit
__kerjmp_HuPadInit:
	b _HuPadInit
	.globl __kerjmp_HuPadRead
__kerjmp_HuPadRead:
	b _HuPadRead
	.globl __kerjmp_HuPadRumbleSet
__kerjmp_HuPadRumbleSet:
	b _HuPadRumbleSet
	.globl __kerjmp_HuPadRumbleStop
__kerjmp_HuPadRumbleStop:
	b _HuPadRumbleStop
	.globl __kerjmp_HuPadRumbleAllStop
__kerjmp_HuPadRumbleAllStop:
	b _HuPadRumbleAllStop
	.globl __kerjmp_HuPadStatGet
__kerjmp_HuPadStatGet:
	b _HuPadStatGet
	.globl __kerjmp_HuPadRumbleGet
__kerjmp_HuPadRumbleGet:
	b _HuPadRumbleGet
	.globl __kerjmp_Hu3DCameraCreate
__kerjmp_Hu3DCameraCreate:
	b _Hu3DCameraCreate
	.globl __kerjmp_Hu3DCameraPerspectiveSet
__kerjmp_Hu3DCameraPerspectiveSet:
	b _Hu3DCameraPerspectiveSet
	.globl __kerjmp_Hu3DCameraViewportSet
__kerjmp_Hu3DCameraViewportSet:
	b _Hu3DCameraViewportSet
	.globl __kerjmp_Hu3DCameraScissorSet
__kerjmp_Hu3DCameraScissorSet:
	b _Hu3DCameraScissorSet
	.globl __kerjmp_Hu3DCameraPosSet
__kerjmp_Hu3DCameraPosSet:
	b _Hu3DCameraPosSet
	.globl __kerjmp_Hu3DCameraKill
__kerjmp_Hu3DCameraKill:
	b _Hu3DCameraKill
	.globl __kerjmp_Hu3DCameraPosSetV
__kerjmp_Hu3DCameraPosSetV:
	b _Hu3DCameraPosSetV
	.globl __kerjmp_Hu3DCameraAllKill
__kerjmp_Hu3DCameraAllKill:
	b _Hu3DCameraAllKill
	.globl __kerjmp_Hu3DCameraSet
__kerjmp_Hu3DCameraSet:
	b _Hu3DCameraSet
	.globl __kerjmp_Hu3DCameraMotionOn
__kerjmp_Hu3DCameraMotionOn:
	b _Hu3DCameraMotionOn
	.globl __kerjmp_Hu3DCameraMotionStart
__kerjmp_Hu3DCameraMotionStart:
	b _Hu3DCameraMotionStart
	.globl __kerjmp_Hu3DCameraMotionOff
__kerjmp_Hu3DCameraMotionOff:
	b _Hu3DCameraMotionOff
	.globl __kerjmp_Hu3DModelCameraCreate
__kerjmp_Hu3DModelCameraCreate:
	b _Hu3DModelCameraCreate
	.globl __kerjmp_Hu3DModelCameraInfoSet
__kerjmp_Hu3DModelCameraInfoSet:
	b _Hu3DModelCameraInfoSet
	.globl __kerjmp_Hu3DLighInit
__kerjmp_Hu3DLighInit:
	b _Hu3DLighInit
	.globl __kerjmp_Hu3DGLightCreate
__kerjmp_Hu3DGLightCreate:
	b _Hu3DGLightCreate
	.globl __kerjmp_Hu3DGLightCreateV
__kerjmp_Hu3DGLightCreateV:
	b _Hu3DGLightCreateV
	.globl __kerjmp_Hu3DGLightKill
__kerjmp_Hu3DGLightKill:
	b _Hu3DGLightKill
	.globl __kerjmp_Hu3DLightAllKill
__kerjmp_Hu3DLightAllKill:
	b _Hu3DLightAllKill
	.globl __kerjmp_Hu3DLightSet
__kerjmp_Hu3DLightSet:
	b _Hu3DLightSet
	.globl __kerjmp_Hu3DGLightSpotSet
__kerjmp_Hu3DGLightSpotSet:
	b _Hu3DGLightSpotSet
	.globl __kerjmp_Hu3DGLightInfinitytSet
__kerjmp_Hu3DGLightInfinitytSet:
	b _Hu3DGLightInfinitytSet
	.globl __kerjmp_Hu3DGLightPointSet
__kerjmp_Hu3DGLightPointSet:
	b _Hu3DGLightPointSet
	.globl __kerjmp_Hu3DGLightColorSet
__kerjmp_Hu3DGLightColorSet:
	b _Hu3DGLightColorSet
	.globl __kerjmp_Hu3DGLightPosSetV
__kerjmp_Hu3DGLightPosSetV:
	b _Hu3DGLightPosSetV
	.globl __kerjmp_Hu3DGLightPosSet
__kerjmp_Hu3DGLightPosSet:
	b _Hu3DGLightPosSet
	.globl __kerjmp_Hu3DGLightPosAimSetV
__kerjmp_Hu3DGLightPosAimSetV:
	b _Hu3DGLightPosAimSetV
	.globl __kerjmp_Hu3DGLightPosAimSet
__kerjmp_Hu3DGLightPosAimSet:
	b _Hu3DGLightPosAimSet
	.globl __kerjmp_Hu3DGLightStaticSet
__kerjmp_Hu3DGLightStaticSet:
	b _Hu3DGLightStaticSet
	.globl __kerjmp_Hu3DModelLightInfoSet
__kerjmp_Hu3DModelLightInfoSet:
	b _Hu3DModelLightInfoSet
	.globl __kerjmp_Hu3DReflectMapSet
__kerjmp_Hu3DReflectMapSet:
	b _Hu3DReflectMapSet
	.globl __kerjmp_Hu3DReflectNoSet
__kerjmp_Hu3DReflectNoSet:
	b _Hu3DReflectNoSet
	.globl __kerjmp_Hu3DFogSet
__kerjmp_Hu3DFogSet:
	b _Hu3DFogSet
	.globl __kerjmp_Hu3DFogClear
__kerjmp_Hu3DFogClear:
	b _Hu3DFogClear
	.globl __kerjmp_Hu3DModelObjPtrGet
__kerjmp_Hu3DModelObjPtrGet:
	b _Hu3DModelObjPtrGet
	.globl __kerjmp_Hu3DModelShadowSet
__kerjmp_Hu3DModelShadowSet:
	b _Hu3DModelShadowSet
	.globl __kerjmp_Hu3DModelShadowReset
__kerjmp_Hu3DModelShadowReset:
	b _Hu3DModelShadowReset
	.globl __kerjmp_Hu3DShadowCreate
__kerjmp_Hu3DShadowCreate:
	b _Hu3DShadowCreate
	.globl __kerjmp_Hu3DShadowPosSet
__kerjmp_Hu3DShadowPosSet:
	b _Hu3DShadowPosSet
	.globl __kerjmp_Hu3DShadowTPLvlSet
__kerjmp_Hu3DShadowTPLvlSet:
	b _Hu3DShadowTPLvlSet
	.globl __kerjmp_Hu3DModelShadowMapSet
__kerjmp_Hu3DModelShadowMapSet:
	b _Hu3DModelShadowMapSet
	.globl __kerjmp_Hu3DModelShadowMapObjSet
__kerjmp_Hu3DModelShadowMapObjSet:
	b _Hu3DModelShadowMapObjSet
	.globl __kerjmp_Hu3DShadowSizeSet
__kerjmp_Hu3DShadowSizeSet:
	b _Hu3DShadowSizeSet
	.globl __kerjmp_Hu3DMipMapSet
__kerjmp_Hu3DMipMapSet:
	b _Hu3DMipMapSet
	.globl __kerjmp_Hu3DModelClusterAttrSet
__kerjmp_Hu3DModelClusterAttrSet:
	b _Hu3DModelClusterAttrSet
	.globl __kerjmp_Hu3DModelClusterAttrReset
__kerjmp_Hu3DModelClusterAttrReset:
	b _Hu3DModelClusterAttrReset
	.globl __kerjmp_Hu3DLLightCreate
__kerjmp_Hu3DLLightCreate:
	b _Hu3DLLightCreate
	.globl __kerjmp_Hu3DLLightCreateV
__kerjmp_Hu3DLLightCreateV:
	b _Hu3DLLightCreateV
	.globl __kerjmp_Hu3DLLightSpotSet
__kerjmp_Hu3DLLightSpotSet:
	b _Hu3DLLightSpotSet
	.globl __kerjmp_Hu3DLLightInfinitytSet
__kerjmp_Hu3DLLightInfinitytSet:
	b _Hu3DLLightInfinitytSet
	.globl __kerjmp_Hu3DLLightPointSet
__kerjmp_Hu3DLLightPointSet:
	b _Hu3DLLightPointSet
	.globl __kerjmp_Hu3DLLightKill
__kerjmp_Hu3DLLightKill:
	b _Hu3DLLightKill
	.globl __kerjmp_Hu3DLLightColorSet
__kerjmp_Hu3DLLightColorSet:
	b _Hu3DLLightColorSet
	.globl __kerjmp_Hu3DLLightPosSetV
__kerjmp_Hu3DLLightPosSetV:
	b _Hu3DLLightPosSetV
	.globl __kerjmp_Hu3DLLightPosSet
__kerjmp_Hu3DLLightPosSet:
	b _Hu3DLLightPosSet
	.globl __kerjmp_Hu3DLLightPosAimSetV
__kerjmp_Hu3DLLightPosAimSetV:
	b _Hu3DLLightPosAimSetV
	.globl __kerjmp_Hu3DLLightPosAimSet
__kerjmp_Hu3DLLightPosAimSet:
	b _Hu3DLLightPosAimSet
	.globl __kerjmp_Hu3DLLightStaticSet
__kerjmp_Hu3DLLightStaticSet:
	b _Hu3DLLightStaticSet
	.globl __kerjmp_Hu3DAnimInit
__kerjmp_Hu3DAnimInit:
	b _Hu3DAnimInit
	.globl __kerjmp_Hu3DAnimCreate
__kerjmp_Hu3DAnimCreate:
	b _Hu3DAnimCreate
	.globl __kerjmp_Hu3DAnimLink
__kerjmp_Hu3DAnimLink:
	b _Hu3DAnimLink
	.globl __kerjmp_Hu3DAnimKill
__kerjmp_Hu3DAnimKill:
	b _Hu3DAnimKill
	.globl __kerjmp_Hu3DAnimAllKill
__kerjmp_Hu3DAnimAllKill:
	b _Hu3DAnimAllKill
	.globl __kerjmp_Hu3DAnimSet
__kerjmp_Hu3DAnimSet:
	b _Hu3DAnimSet
	.globl __kerjmp_Hu3DAnimExec
__kerjmp_Hu3DAnimExec:
	b _Hu3DAnimExec
	.globl __kerjmp_Hu3DAnimAttrSet
__kerjmp_Hu3DAnimAttrSet:
	b _Hu3DAnimAttrSet
	.globl __kerjmp_Hu3DAnimAttrReset
__kerjmp_Hu3DAnimAttrReset:
	b _Hu3DAnimAttrReset
	.globl __kerjmp_Hu3DAnimSpeedSet
__kerjmp_Hu3DAnimSpeedSet:
	b _Hu3DAnimSpeedSet
	.globl __kerjmp_Hu3DAnimBankSet
__kerjmp_Hu3DAnimBankSet:
	b _Hu3DAnimBankSet
	.globl __kerjmp_Hu3DAnmNoSet
__kerjmp_Hu3DAnmNoSet:
	b _Hu3DAnmNoSet
	.globl __kerjmp_Hu3DTexScrollCreate
__kerjmp_Hu3DTexScrollCreate:
	b _Hu3DTexScrollCreate
	.globl __kerjmp_Hu3DTexScrollPosSet
__kerjmp_Hu3DTexScrollPosSet:
	b _Hu3DTexScrollPosSet
	.globl __kerjmp_Hu3DTexScrollPosMoveSet
__kerjmp_Hu3DTexScrollPosMoveSet:
	b _Hu3DTexScrollPosMoveSet
	.globl __kerjmp_Hu3DTexScrollRotSet
__kerjmp_Hu3DTexScrollRotSet:
	b _Hu3DTexScrollRotSet
	.globl __kerjmp_Hu3DTexScrollRotMoveSet
__kerjmp_Hu3DTexScrollRotMoveSet:
	b _Hu3DTexScrollRotMoveSet
	.globl __kerjmp_Hu3DTexScrollKill
__kerjmp_Hu3DTexScrollKill:
	b _Hu3DTexScrollKill
	.globl __kerjmp_Hu3DTexScrollAllKill
__kerjmp_Hu3DTexScrollAllKill:
	b _Hu3DTexScrollAllKill
	.globl __kerjmp_Hu3DTexScrollPauseDisableSet
__kerjmp_Hu3DTexScrollPauseDisableSet:
	b _Hu3DTexScrollPauseDisableSet
	.globl __kerjmp_Hu3DParticleCreate
__kerjmp_Hu3DParticleCreate:
	b _Hu3DParticleCreate
	.globl __kerjmp_Hu3DParticleScaleSet
__kerjmp_Hu3DParticleScaleSet:
	b _Hu3DParticleScaleSet
	.globl __kerjmp_Hu3DParticleZRotSet
__kerjmp_Hu3DParticleZRotSet:
	b _Hu3DParticleZRotSet
	.globl __kerjmp_Hu3DParticleColSet
__kerjmp_Hu3DParticleColSet:
	b _Hu3DParticleColSet
	.globl __kerjmp_Hu3DParticleTPLvlSet
__kerjmp_Hu3DParticleTPLvlSet:
	b _Hu3DParticleTPLvlSet
	.globl __kerjmp_Hu3DParticleBlendModeSet
__kerjmp_Hu3DParticleBlendModeSet:
	b _Hu3DParticleBlendModeSet
	.globl __kerjmp_Hu3DParticleHookSet
__kerjmp_Hu3DParticleHookSet:
	b _Hu3DParticleHookSet
	.globl __kerjmp_Hu3DParticleCntSet
__kerjmp_Hu3DParticleCntSet:
	b _Hu3DParticleCntSet
	.globl __kerjmp_Hu3DParticleAttrSet
__kerjmp_Hu3DParticleAttrSet:
	b _Hu3DParticleAttrSet
	.globl __kerjmp_Hu3DParticleAttrReset
__kerjmp_Hu3DParticleAttrReset:
	b _Hu3DParticleAttrReset
	.globl __kerjmp_Hu3DParticleAnimModeSet
__kerjmp_Hu3DParticleAnimModeSet:
	b _Hu3DParticleAnimModeSet
	.globl __kerjmp_Hu3DParManInit
__kerjmp_Hu3DParManInit:
	b _Hu3DParManInit
	.globl __kerjmp_Hu3DParManCreate
__kerjmp_Hu3DParManCreate:
	b _Hu3DParManCreate
	.globl __kerjmp_Hu3DParManKill
__kerjmp_Hu3DParManKill:
	b _Hu3DParManKill
	.globl __kerjmp_Hu3DParManAllKill
__kerjmp_Hu3DParManAllKill:
	b _Hu3DParManAllKill
	.globl __kerjmp_Hu3DParManPtrGet
__kerjmp_Hu3DParManPtrGet:
	b _Hu3DParManPtrGet
	.globl __kerjmp_Hu3DParManAttrSet
__kerjmp_Hu3DParManAttrSet:
	b _Hu3DParManAttrSet
	.globl __kerjmp_Hu3DParManAttrReset
__kerjmp_Hu3DParManAttrReset:
	b _Hu3DParManAttrReset
	.globl __kerjmp_Hu3DParManPosSet
__kerjmp_Hu3DParManPosSet:
	b _Hu3DParManPosSet
	.globl __kerjmp_Hu3DParManVecSet
__kerjmp_Hu3DParManVecSet:
	b _Hu3DParManVecSet
	.globl __kerjmp_Hu3DParManRotSet
__kerjmp_Hu3DParManRotSet:
	b _Hu3DParManRotSet
	.globl __kerjmp_Hu3DParManModelIDGet
__kerjmp_Hu3DParManModelIDGet:
	b _Hu3DParManModelIDGet
	.globl __kerjmp_Hu3DParManLink
__kerjmp_Hu3DParManLink:
	b _Hu3DParManLink
	.globl __kerjmp_Hu3DParManTimeLimitSet
__kerjmp_Hu3DParManTimeLimitSet:
	b _Hu3DParManTimeLimitSet
	.globl __kerjmp_Hu3DParManColorSet
__kerjmp_Hu3DParManColorSet:
	b _Hu3DParManColorSet
	.globl __kerjmp_Hu3DMotionCreate
__kerjmp_Hu3DMotionCreate:
	b _Hu3DMotionCreate
	.globl __kerjmp_Hu3DMotionInit
__kerjmp_Hu3DMotionInit:
	b _Hu3DMotionInit
	.globl __kerjmp_Hu3DMotionModelCreate
__kerjmp_Hu3DMotionModelCreate:
	b _Hu3DMotionModelCreate
	.globl __kerjmp_Hu3DMotionKill
__kerjmp_Hu3DMotionKill:
	b _Hu3DMotionKill
	.globl __kerjmp_Hu3DMotionAllKill
__kerjmp_Hu3DMotionAllKill:
	b _Hu3DMotionAllKill
	.globl __kerjmp_Hu3DMotionSet
__kerjmp_Hu3DMotionSet:
	b _Hu3DMotionSet
	.globl __kerjmp_Hu3DMotionExec
__kerjmp_Hu3DMotionExec:
	b _Hu3DMotionExec
	.globl __kerjmp_Hu3DSubMotionExec
__kerjmp_Hu3DSubMotionExec:
	b _Hu3DSubMotionExec
	.globl __kerjmp_Hu3DMotionNext
__kerjmp_Hu3DMotionNext:
	b _Hu3DMotionNext
	.globl __kerjmp_Hu3DMotionTimeSet
__kerjmp_Hu3DMotionTimeSet:
	b _Hu3DMotionTimeSet
	.globl __kerjmp_Hu3DMotionTimeGet
__kerjmp_Hu3DMotionTimeGet:
	b _Hu3DMotionTimeGet
	.globl __kerjmp_Hu3DMotionMaxTimeGet
__kerjmp_Hu3DMotionMaxTimeGet:
	b _Hu3DMotionMaxTimeGet
	.globl __kerjmp_Hu3DMotionStartEndSet
__kerjmp_Hu3DMotionStartEndSet:
	b _Hu3DMotionStartEndSet
	.globl __kerjmp_Hu3DMotionMotionMaxTimeGet
__kerjmp_Hu3DMotionMotionMaxTimeGet:
	b _Hu3DMotionMotionMaxTimeGet
	.globl __kerjmp_Hu3DMotionEndCheck
__kerjmp_Hu3DMotionEndCheck:
	b _Hu3DMotionEndCheck
	.globl __kerjmp_Hu3DMotionShiftSet
__kerjmp_Hu3DMotionShiftSet:
	b _Hu3DMotionShiftSet
	.globl __kerjmp_Hu3DMotionIDGet
__kerjmp_Hu3DMotionIDGet:
	b _Hu3DMotionIDGet
	.globl __kerjmp_Hu3DMotionShiftIDGet
__kerjmp_Hu3DMotionShiftIDGet:
	b _Hu3DMotionShiftIDGet
	.globl __kerjmp_Hu3DMotionShiftTimeGet
__kerjmp_Hu3DMotionShiftTimeGet:
	b _Hu3DMotionShiftTimeGet
	.globl __kerjmp_Hu3DMotionShiftMaxTimeGet
__kerjmp_Hu3DMotionShiftMaxTimeGet:
	b _Hu3DMotionShiftMaxTimeGet
	.globl __kerjmp_Hu3DMotionShiftStartEndSet
__kerjmp_Hu3DMotionShiftStartEndSet:
	b _Hu3DMotionShiftStartEndSet
	.globl __kerjmp_Hu3DMotionShiftSpeedSet
__kerjmp_Hu3DMotionShiftSpeedSet:
	b _Hu3DMotionShiftSpeedSet
	.globl __kerjmp_Hu3DMotionSpeedSet
__kerjmp_Hu3DMotionSpeedSet:
	b _Hu3DMotionSpeedSet
	.globl __kerjmp_Hu3DMotionShapeSpeedSet
__kerjmp_Hu3DMotionShapeSpeedSet:
	b _Hu3DMotionShapeSpeedSet
	.globl __kerjmp_Hu3DMotionShapeTimeSet
__kerjmp_Hu3DMotionShapeTimeSet:
	b _Hu3DMotionShapeTimeSet
	.globl __kerjmp_Hu3DMotionNoMotSet
__kerjmp_Hu3DMotionNoMotSet:
	b _Hu3DMotionNoMotSet
	.globl __kerjmp_Hu3DMotionNoMotReset
__kerjmp_Hu3DMotionNoMotReset:
	b _Hu3DMotionNoMotReset
	.globl __kerjmp_Hu3DMotionForceSet
__kerjmp_Hu3DMotionForceSet:
	b _Hu3DMotionForceSet
	.globl __kerjmp_Hu3DMotionShapeSet
__kerjmp_Hu3DMotionShapeSet:
	b _Hu3DMotionShapeSet
	.globl __kerjmp_Hu3DMotionShapeIDGet
__kerjmp_Hu3DMotionShapeIDGet:
	b _Hu3DMotionShapeIDGet
	.globl __kerjmp_Hu3DMotionShapeMaxTimeGet
__kerjmp_Hu3DMotionShapeMaxTimeGet:
	b _Hu3DMotionShapeMaxTimeGet
	.globl __kerjmp_Hu3DMotionClusterSet
__kerjmp_Hu3DMotionClusterSet:
	b _Hu3DMotionClusterSet
	.globl __kerjmp_Hu3DMotionClusterNoSet
__kerjmp_Hu3DMotionClusterNoSet:
	b _Hu3DMotionClusterNoSet
	.globl __kerjmp_Hu3DMotionShapeReset
__kerjmp_Hu3DMotionShapeReset:
	b _Hu3DMotionShapeReset
	.globl __kerjmp_Hu3DMotionClusterReset
__kerjmp_Hu3DMotionClusterReset:
	b _Hu3DMotionClusterReset
	.globl __kerjmp_Hu3DJointMotion
__kerjmp_Hu3DJointMotion:
	b _Hu3DJointMotion
	.globl __kerjmp_Hu3DMotionOverlaySet
__kerjmp_Hu3DMotionOverlaySet:
	b _Hu3DMotionOverlaySet
	.globl __kerjmp_Hu3DMotionOverlayReset
__kerjmp_Hu3DMotionOverlayReset:
	b _Hu3DMotionOverlayReset
	.globl __kerjmp_Hu3DMotionOverlayTimeGet
__kerjmp_Hu3DMotionOverlayTimeGet:
	b _Hu3DMotionOverlayTimeGet
	.globl __kerjmp_Hu3DMotionOverlayTimeSet
__kerjmp_Hu3DMotionOverlayTimeSet:
	b _Hu3DMotionOverlayTimeSet
	.globl __kerjmp_Hu3DMotionOverlaySpeedSet
__kerjmp_Hu3DMotionOverlaySpeedSet:
	b _Hu3DMotionOverlaySpeedSet
	.globl __kerjmp_Hu3DModelObjDrawInit
__kerjmp_Hu3DModelObjDrawInit:
	b _Hu3DModelObjDrawInit
	.globl __kerjmp_Hu3DModelObjDraw
__kerjmp_Hu3DModelObjDraw:
	b _Hu3DModelObjDraw
	.globl __kerjmp_Hu3DMotionCalc
__kerjmp_Hu3DMotionCalc:
	b _Hu3DMotionCalc
	.globl __kerjmp_Hu3DMotionShapeStartEndSet
__kerjmp_Hu3DMotionShapeStartEndSet:
	b _Hu3DMotionShapeStartEndSet
	.globl __kerjmp_CamMotionEx
__kerjmp_CamMotionEx:
	b _CamMotionEx
	.globl __kerjmp_CamMotionEx2
__kerjmp_CamMotionEx2:
	b _CamMotionEx2
	.globl __kerjmp_Hu3D2Dto3D
__kerjmp_Hu3D2Dto3D:
	b _Hu3D2Dto3D
	.globl __kerjmp_Hu3D3Dto2D
__kerjmp_Hu3D3Dto2D:
	b _Hu3D3Dto2D
	.globl __kerjmp_Hu3DMtxRotGet
__kerjmp_Hu3DMtxRotGet:
	b _Hu3DMtxRotGet
	.globl __kerjmp_Hu3DMtxTransGet
__kerjmp_Hu3DMtxTransGet:
	b _Hu3DMtxTransGet
	.globl __kerjmp_Hu3DMtxScaleGet
__kerjmp_Hu3DMtxScaleGet:
	b _Hu3DMtxScaleGet
	.globl __kerjmp_Hu3DProjectionCreate
__kerjmp_Hu3DProjectionCreate:
	b _Hu3DProjectionCreate
	.globl __kerjmp_Hu3DProjectionPosSet
__kerjmp_Hu3DProjectionPosSet:
	b _Hu3DProjectionPosSet
	.globl __kerjmp_Hu3DProjectionTPLvlSet
__kerjmp_Hu3DProjectionTPLvlSet:
	b _Hu3DProjectionTPLvlSet
	.globl __kerjmp_Hu3DProjectionKill
__kerjmp_Hu3DProjectionKill:
	b _Hu3DProjectionKill
	.globl __kerjmp_HuAudInit
__kerjmp_HuAudInit:
	b _HuAudInit
	.globl __kerjmp_HuAudStreamPlay
__kerjmp_HuAudStreamPlay:
	b _HuAudStreamPlay
	.globl __kerjmp_HuAudAllStop
__kerjmp_HuAudAllStop:
	b _HuAudAllStop
	.globl __kerjmp_HuAudFadeOut
__kerjmp_HuAudFadeOut:
	b _HuAudFadeOut
	.globl __kerjmp_HuAudStreamPauseOn
__kerjmp_HuAudStreamPauseOn:
	b _HuAudStreamPauseOn
	.globl __kerjmp_HuAudStreamPauseOff
__kerjmp_HuAudStreamPauseOff:
	b _HuAudStreamPauseOff
	.globl __kerjmp_HuAudStreamFadeOut
__kerjmp_HuAudStreamFadeOut:
	b _HuAudStreamFadeOut
	.globl __kerjmp_HuAudStreamVolSet
__kerjmp_HuAudStreamVolSet:
	b _HuAudStreamVolSet
	.globl __kerjmp_HuAudFXPlay
__kerjmp_HuAudFXPlay:
	b _HuAudFXPlay
	.globl __kerjmp_HuAudFXPlayVol
__kerjmp_HuAudFXPlayVol:
	b _HuAudFXPlayVol
	.globl __kerjmp_HuAudFXPlayVolPan
__kerjmp_HuAudFXPlayVolPan:
	b _HuAudFXPlayVolPan
	.globl __kerjmp_HuAudFXStop
__kerjmp_HuAudFXStop:
	b _HuAudFXStop
	.globl __kerjmp_HuAudFXFadeOut
__kerjmp_HuAudFXFadeOut:
	b _HuAudFXFadeOut
	.globl __kerjmp_HuAudFXPanning
__kerjmp_HuAudFXPanning:
	b _HuAudFXPanning
	.globl __kerjmp_HuAudSeqPlay
__kerjmp_HuAudSeqPlay:
	b _HuAudSeqPlay
	.globl __kerjmp_HuAudSeqStop
__kerjmp_HuAudSeqStop:
	b _HuAudSeqStop
	.globl __kerjmp_HuAudSeqFadeOut
__kerjmp_HuAudSeqFadeOut:
	b _HuAudSeqFadeOut
	.globl __kerjmp_HuAudSeqMidiCtrlGet
__kerjmp_HuAudSeqMidiCtrlGet:
	b _HuAudSeqMidiCtrlGet
	.globl __kerjmp_HuAudFXListnerSet
__kerjmp_HuAudFXListnerSet:
	b _HuAudFXListnerSet
	.globl __kerjmp_HuAudFXListnerUpdate
__kerjmp_HuAudFXListnerUpdate:
	b _HuAudFXListnerUpdate
	.globl __kerjmp_HuAudFXEmiterPlay
__kerjmp_HuAudFXEmiterPlay:
	b _HuAudFXEmiterPlay
	.globl __kerjmp_HuAudFXEmiterUpDate
__kerjmp_HuAudFXEmiterUpDate:
	b _HuAudFXEmiterUpDate
	.globl __kerjmp_HuAudFXListnerKill
__kerjmp_HuAudFXListnerKill:
	b _HuAudFXListnerKill
	.globl __kerjmp_HuAudFXStatusGet
__kerjmp_HuAudFXStatusGet:
	b _HuAudFXStatusGet
	.globl __kerjmp_HuAudFXPitchSet
__kerjmp_HuAudFXPitchSet:
	b _HuAudFXPitchSet
	.globl __kerjmp_HuAudFXVolSet
__kerjmp_HuAudFXVolSet:
	b _HuAudFXVolSet
	.globl __kerjmp_HuAudDllSndGrpSet
__kerjmp_HuAudDllSndGrpSet:
	b _HuAudDllSndGrpSet
	.globl __kerjmp_HuAudSndGrpSetSet
__kerjmp_HuAudSndGrpSetSet:
	b _HuAudSndGrpSetSet
	.globl __kerjmp_HuAudSndGrpSet
__kerjmp_HuAudSndGrpSet:
	b _HuAudSndGrpSet
	.globl __kerjmp_HuAudSndCommonGrpSet
__kerjmp_HuAudSndCommonGrpSet:
	b _HuAudSndCommonGrpSet
	.globl __kerjmp_HuAudSStreamPlay
__kerjmp_HuAudSStreamPlay:
	b _HuAudSStreamPlay
	.globl __kerjmp_HuAudSStreamStop
__kerjmp_HuAudSStreamStop:
	b _HuAudSStreamStop
	.globl __kerjmp_HuAudSStreamFadeOut
__kerjmp_HuAudSStreamFadeOut:
	b _HuAudSStreamFadeOut
	.globl __kerjmp_HuAudSStreamAllFadeOut
__kerjmp_HuAudSStreamAllFadeOut:
	b _HuAudSStreamAllFadeOut
	.globl __kerjmp_HuAudSStreamAllStop
__kerjmp_HuAudSStreamAllStop:
	b _HuAudSStreamAllStop
	.globl __kerjmp_HuAudSStreamStatGet
__kerjmp_HuAudSStreamStatGet:
	b _HuAudSStreamStatGet
	.globl __kerjmp_HuAudPlayerVoicePlay
__kerjmp_HuAudPlayerVoicePlay:
	b _PlayerFXPlay
	.globl __kerjmp_HuAudCharVoicePlay
__kerjmp_HuAudCharVoicePlay:
	b _CharFXPlay
	.globl __kerjmp_HuAudPlayerVoicePlayPos
__kerjmp_HuAudPlayerVoicePlayPos:
	b _PlayerFXPlayPos
	.globl __kerjmp_CharFXPlayPos
__kerjmp_CharFXPlayPos:
	b _CharFXPlayPos
	.globl __kerjmp_HuAudPlayerVoicePlayEntry
__kerjmp_HuAudPlayerVoicePlayEntry:
	b _PlayerFXStop
	.globl __kerjmp_CharFXStop
__kerjmp_CharFXStop:
	b _CharFXStop
	.globl __kerjmp_HuAudAUXSet
__kerjmp_HuAudAUXSet:
	b _HuAudAUXSet
	.globl __kerjmp_msmMusPlay
__kerjmp_msmMusPlay:
	b _msmMusPlay
	.globl __kerjmp_espInit
__kerjmp_espInit:
	b _espInit
	.globl __kerjmp_espEntry
__kerjmp_espEntry:
	b _espEntry
	.globl __kerjmp_espKill
__kerjmp_espKill:
	b _espKill
	.globl __kerjmp_espGrpIDGet
__kerjmp_espGrpIDGet:
	b _espGrpIDGet
	.globl __kerjmp_espDispOn
__kerjmp_espDispOn:
	b _espDispOn
	.globl __kerjmp_espDispOff
__kerjmp_espDispOff:
	b _espDispOff
	.globl __kerjmp_espAttrSet
__kerjmp_espAttrSet:
	b _espAttrSet
	.globl __kerjmp_espAttrReset
__kerjmp_espAttrReset:
	b _espAttrReset
	.globl __kerjmp_espPosSet
__kerjmp_espPosSet:
	b _espPosSet
	.globl __kerjmp_espScaleSet
__kerjmp_espScaleSet:
	b _espScaleSet
	.globl __kerjmp_espZRotSet
__kerjmp_espZRotSet:
	b _espZRotSet
	.globl __kerjmp_espTPLvlSet
__kerjmp_espTPLvlSet:
	b _espTPLvlSet
	.globl __kerjmp_espColorSet
__kerjmp_espColorSet:
	b _espColorSet
	.globl __kerjmp_espSpeedSet
__kerjmp_espSpeedSet:
	b _espSpeedSet
	.globl __kerjmp_espBankSet
__kerjmp_espBankSet:
	b _espBankSet
	.globl __kerjmp_espDrawNoSet
__kerjmp_espDrawNoSet:
	b _espDrawNoSet
	.globl __kerjmp_espPriSet
__kerjmp_espPriSet:
	b _espPriSet
	.globl __kerjmp_modelTable
__kerjmp_modelTable:
	b _modelTable
	.globl __kerjmp_motionTable
__kerjmp_motionTable:
	b _motionTable
	.globl __kerjmp_spriteTable
__kerjmp_spriteTable:
	b _spriteTable
	.globl __kerjmp_lbl_801D3DA0
__kerjmp_lbl_801D3DA0:
	b _lbl_801D3DA0
	.globl __kerjmp_fn_8003FF68
__kerjmp_fn_8003FF68:
	b _fn_8003FF68
	.globl __kerjmp_HuPrcInit
__kerjmp_HuPrcInit:
	b _HuPrcInit
	.globl __kerjmp_HuPrcCall
__kerjmp_HuPrcCall:
	b _HuPrcCall
	.globl __kerjmp_HuPrcCreate
__kerjmp_HuPrcCreate:
	b _HuPrcCreate
	.globl __kerjmp_HuPrcKill
__kerjmp_HuPrcKill:
	b _HuPrcKill
	.globl __kerjmp_HuPrcEnd
__kerjmp_HuPrcEnd:
	b _HuPrcEnd
	.globl __kerjmp_HuPrcWakeup
__kerjmp_HuPrcWakeup:
	b _HuPrcWakeup
	.globl __kerjmp_HuPrcSleep
__kerjmp_HuPrcSleep:
	b _HuPrcSleep
	.globl __kerjmp_HuPrcVSleep
__kerjmp_HuPrcVSleep:
	b _HuPrcVSleep
	.globl __kerjmp_HuPrcCurrentGet
__kerjmp_HuPrcCurrentGet:
	b _HuPrcCurrentGet
	.globl __kerjmp_HuPrcDestructorSet
__kerjmp_HuPrcDestructorSet:
	b _HuPrcDestructorSet
	.globl __kerjmp_HuPrcDestructorSet2
__kerjmp_HuPrcDestructorSet2:
	b _HuPrcDestructorSet2
	.globl __kerjmp_HuPrcChildCreate
__kerjmp_HuPrcChildCreate:
	b _HuPrcChildCreate
	.globl __kerjmp_HuPrcChildLink
__kerjmp_HuPrcChildLink:
	b _HuPrcChildLink
	.globl __kerjmp_HuPrcChildUnlink
__kerjmp_HuPrcChildUnlink:
	b _HuPrcChildUnlink
	.globl __kerjmp_HuPrcChildKill
__kerjmp_HuPrcChildKill:
	b _HuPrcChildKill
	.globl __kerjmp_HuPrcMemAlloc
__kerjmp_HuPrcMemAlloc:
	b _HuPrcMemAlloc
	.globl __kerjmp_HuPrcMemFree
__kerjmp_HuPrcMemFree:
	b _HuPrcMemFree
	.globl __kerjmp_Hu3DParManVacumeSet
__kerjmp_Hu3DParManVacumeSet:
	b _Hu3DParManVacumeSet
	.globl __kerjmp_HuDataInit
__kerjmp_HuDataInit:
	b _HuDataInit
	.globl __kerjmp_HuDataDirRead
__kerjmp_HuDataDirRead:
	b _HuDataDirRead
	.globl __kerjmp_HuDataRead
__kerjmp_HuDataRead:
	b _HuDataRead
	.globl __kerjmp_HuDataReadNum
__kerjmp_HuDataReadNum:
	b _HuDataReadNum
	.globl __kerjmp_HuDataReadMulti
__kerjmp_HuDataReadMulti:
	b _HuDataReadMulti
	.globl __kerjmp_HuDataDirReadAsync
__kerjmp_HuDataDirReadAsync:
	b _HuDataDirReadAsync
	.globl __kerjmp_HuDataDirReadNumAsync
__kerjmp_HuDataDirReadNumAsync:
	b _HuDataDirReadNumAsync
	.globl __kerjmp_HuDataSelHeapRead
__kerjmp_HuDataSelHeapRead:
	b _HuDataSelHeapRead
	.globl __kerjmp_HuDataSelHeapReadNum
__kerjmp_HuDataSelHeapReadNum:
	b _HuDataSelHeapReadNum
	.globl __kerjmp_HuDataGetSize
__kerjmp_HuDataGetSize:
	b _HuDataGetSize
	.globl __kerjmp_HuDataDirClose
__kerjmp_HuDataDirClose:
	b _HuDataDirClose
	.globl __kerjmp_HuDataDirCloseNum
__kerjmp_HuDataDirCloseNum:
	b _HuDataDirCloseNum
	.globl __kerjmp_HuDataClose
__kerjmp_HuDataClose:
	b _HuDataClose
	.globl __kerjmp_HuDataCloseMulti
__kerjmp_HuDataCloseMulti:
	b _HuDataCloseMulti
	.globl __kerjmp_HuDataReadNumHeapShortForce
__kerjmp_HuDataReadNumHeapShortForce:
	b _HuDataReadNumHeapShortForce
	.globl __kerjmp_ARRegisterDMACallback
__kerjmp_ARRegisterDMACallback:
	b _ARRegisterDMACallback
	.globl __kerjmp_ARGetDMAStatus
__kerjmp_ARGetDMAStatus:
	b _ARGetDMAStatus
	.globl __kerjmp_ARStartDMA
__kerjmp_ARStartDMA:
	b _ARStartDMA
	.globl __kerjmp_ARInit
__kerjmp_ARInit:
	b _ARInit
	.globl __kerjmp_ARAlloc
__kerjmp_ARAlloc:
	b _ARAlloc
	.globl __kerjmp_ARFree
__kerjmp_ARFree:
	b _ARFree
	.globl __kerjmp_ARGetSize
__kerjmp_ARGetSize:
	b _ARGetSize
	.globl __kerjmp_ARSetSize
__kerjmp_ARSetSize:
	b _ARSetSize
	.globl __kerjmp_HuSprBegin
__kerjmp_HuSprBegin:
	b _HuSprBegin
	.globl __kerjmp_HuSprCall
__kerjmp_HuSprCall:
	b _HuSprCall
	.globl __kerjmp_HuSprFinish
__kerjmp_HuSprFinish:
	b _HuSprFinish
	.globl __kerjmp_HuSprAnimRead
__kerjmp_HuSprAnimRead:
	b _HuSprAnimRead
	.globl __kerjmp_HuSprCreate
__kerjmp_HuSprCreate:
	b _HuSprCreate
	.globl __kerjmp_HuSprGrpCreate
__kerjmp_HuSprGrpCreate:
	b _HuSprGrpCreate
	.globl __kerjmp_HuSprGrpMemberSet
__kerjmp_HuSprGrpMemberSet:
	b _HuSprGrpMemberSet
	.globl __kerjmp_HuSprGrpMemberKill
__kerjmp_HuSprGrpMemberKill:
	b _HuSprGrpMemberKill
	.globl __kerjmp_HuSprGrpKill
__kerjmp_HuSprGrpKill:
	b _HuSprGrpKill
	.globl __kerjmp_HuSprKill
__kerjmp_HuSprKill:
	b _HuSprKill
	.globl __kerjmp_HuSprAnimKill
__kerjmp_HuSprAnimKill:
	b _HuSprAnimKill
	.globl __kerjmp_HuSprAttrSet
__kerjmp_HuSprAttrSet:
	b _HuSprAttrSet
	.globl __kerjmp_HuSprAttrReset
__kerjmp_HuSprAttrReset:
	b _HuSprAttrReset
	.globl __kerjmp_HuSprPosSet
__kerjmp_HuSprPosSet:
	b _HuSprPosSet
	.globl __kerjmp_HuSprScaleSet
__kerjmp_HuSprScaleSet:
	b _HuSprScaleSet
	.globl __kerjmp_HuSprZRotSet
__kerjmp_HuSprZRotSet:
	b _HuSprZRotSet
	.globl __kerjmp_HuSprGrpPosSet
__kerjmp_HuSprGrpPosSet:
	b _HuSprGrpPosSet
	.globl __kerjmp_HuSprGrpZRotSet
__kerjmp_HuSprGrpZRotSet:
	b _HuSprGrpZRotSet
	.globl __kerjmp_HuSprGrpScaleSet
__kerjmp_HuSprGrpScaleSet:
	b _HuSprGrpScaleSet
	.globl __kerjmp_HuSprTPLvlSet
__kerjmp_HuSprTPLvlSet:
	b _HuSprTPLvlSet
	.globl __kerjmp_HuSprColorSet
__kerjmp_HuSprColorSet:
	b _HuSprColorSet
	.globl __kerjmp_HuSprSpeedSet
__kerjmp_HuSprSpeedSet:
	b _HuSprSpeedSet
	.globl __kerjmp_HuSprBankSet
__kerjmp_HuSprBankSet:
	b _HuSprBankSet
	.globl __kerjmp_HuSprGrpDrawNoSet
__kerjmp_HuSprGrpDrawNoSet:
	b _HuSprGrpDrawNoSet
	.globl __kerjmp_HuSprDrawNoSet
__kerjmp_HuSprDrawNoSet:
	b _HuSprDrawNoSet
	.globl __kerjmp_HuSprPriSet
__kerjmp_HuSprPriSet:
	b _HuSprPriSet
	.globl __kerjmp_HuSprFuncCreate
__kerjmp_HuSprFuncCreate:
	b _HuSprFuncCreate
	.globl __kerjmp_HuSprAnimMake
__kerjmp_HuSprAnimMake:
	b _HuSprAnimMake
	.globl __kerjmp_HuSprGrpCenterSet
__kerjmp_HuSprGrpCenterSet:
	b _HuSprGrpCenterSet
	.globl __kerjmp_HuSprAnimLock
__kerjmp_HuSprAnimLock:
	b _HuSprAnimLock
	.globl __kerjmp_AnimDebug
__kerjmp_AnimDebug:
	b _AnimDebug
	.globl __kerjmp_HuSprExecLayerSet
__kerjmp_HuSprExecLayerSet:
	b _HuSprExecLayerSet
	.globl __kerjmp_HuSprSprBGSet
__kerjmp_HuSprSprBGSet:
	b _HuSprSprBGSet
	.globl __kerjmp_HuSprBGSet
__kerjmp_HuSprBGSet:
	b _HuSprBGSet
	.globl __kerjmp_HuSprGrpScissorSet
__kerjmp_HuSprGrpScissorSet:
	b _HuSprGrpScissorSet
	.globl __kerjmp_HuSprScissorSet
__kerjmp_HuSprScissorSet:
	b _HuSprScissorSet
	.globl __kerjmp_HuSprGrpTPLvlSet
__kerjmp_HuSprGrpTPLvlSet:
	b _HuSprGrpTPLvlSet
	.globl __kerjmp_HuARMalloc
__kerjmp_HuARMalloc:
	b _HuARMalloc
	.globl __kerjmp_HuARFree
__kerjmp_HuARFree:
	b _HuARFree
	.globl __kerjmp_HuAR_DVDtoARAM
__kerjmp_HuAR_DVDtoARAM:
	b _HuAR_DVDtoARAM
	.globl __kerjmp_HuAR_MRAMtoARAM
__kerjmp_HuAR_MRAMtoARAM:
	b _HuAR_MRAMtoARAM
	.globl __kerjmp_HuAR_MRAMtoARAM2
__kerjmp_HuAR_MRAMtoARAM2:
	b _HuAR_MRAMtoARAM2
	.globl __kerjmp_HuAR_ARAMtoMRAM
__kerjmp_HuAR_ARAMtoMRAM:
	b _HuAR_ARAMtoMRAM
	.globl __kerjmp_HuAR_ARAMtoMRAMNum
__kerjmp_HuAR_ARAMtoMRAMNum:
	b _HuAR_ARAMtoMRAMNum
	.globl __kerjmp_HuARDMACheck
__kerjmp_HuARDMACheck:
	b _HuARDMACheck
	.globl __kerjmp_HuARDirCheck
__kerjmp_HuARDirCheck:
	b _HuARDirCheck
	.globl __kerjmp_HuARDirFree
__kerjmp_HuARDirFree:
	b _HuARDirFree
	.globl __kerjmp_HuAR_ARAMtoMRAMFileRead
__kerjmp_HuAR_ARAMtoMRAMFileRead:
	b _HuAR_ARAMtoMRAMFileRead
	.globl __kerjmp_HuAudFXListnerSetEX
__kerjmp_HuAudFXListnerSetEX:
	b _HuAudFXListnerSetEX
	.globl __kerjmp_HuWindowInit
__kerjmp_HuWindowInit:
	b _HuWindowInit
	.globl __kerjmp_HuWinInit
__kerjmp_HuWinInit:
	b _HuWinInit
	.globl __kerjmp_HuWinCreate
__kerjmp_HuWinCreate:
	b _HuWinCreate
	.globl __kerjmp_HuWinKill
__kerjmp_HuWinKill:
	b _HuWinKill
	.globl __kerjmp_HuWinAllKill
__kerjmp_HuWinAllKill:
	b _HuWinAllKill
	.globl __kerjmp_HuWinMesSet
__kerjmp_HuWinMesSet:
	b _HuWinMesSet
	.globl __kerjmp_HuWinInsertMesSet
__kerjmp_HuWinInsertMesSet:
	b _HuWinInsertMesSet
	.globl __kerjmp_HuWinChoiceGet
__kerjmp_HuWinChoiceGet:
	b _HuWinChoiceGet
	.globl __kerjmp_HuWinChoiceNumGet
__kerjmp_HuWinChoiceNumGet:
	b _HuWinChoiceNumGet
	.globl __kerjmp_HuWinMesWait
__kerjmp_HuWinMesWait:
	b _HuWinMesWait
	.globl __kerjmp_HuWinSprKill
__kerjmp_HuWinSprKill:
	b _HuWinSprKill
	.globl __kerjmp_HuWinMesRead
__kerjmp_HuWinMesRead:
	b _HuWinMesRead
	.globl __kerjmp_HuWinAnimSet
__kerjmp_HuWinAnimSet:
	b _HuWinAnimSet
	.globl __kerjmp_HuWinSprSet
__kerjmp_HuWinSprSet:
	b _HuWinSprSet
	.globl __kerjmp_HuWinSprPosSet
__kerjmp_HuWinSprPosSet:
	b _HuWinSprPosSet
	.globl __kerjmp_HuWinSprIDGet
__kerjmp_HuWinSprIDGet:
	b _HuWinSprIDGet
	.globl __kerjmp_HuWinMesMaxSizeGet
__kerjmp_HuWinMesMaxSizeGet:
	b _HuWinMesMaxSizeGet
	.globl __kerjmp_HuWinInsertMesSizeGet
__kerjmp_HuWinInsertMesSizeGet:
	b _HuWinInsertMesSizeGet
	.globl __kerjmp_HuWinMesMaxSizeBetGet
__kerjmp_HuWinMesMaxSizeBetGet:
	b _HuWinMesMaxSizeBetGet
	.globl __kerjmp_HuWinExCreate
__kerjmp_HuWinExCreate:
	b _HuWinExCreate
	.globl __kerjmp_HuWinDispOn
__kerjmp_HuWinDispOn:
	b _HuWinDispOn
	.globl __kerjmp_HuWinDispOff
__kerjmp_HuWinDispOff:
	b _HuWinDispOff
	.globl __kerjmp_HuWinExAnimIn
__kerjmp_HuWinExAnimIn:
	b _HuWinExAnimIn
	.globl __kerjmp_HuWinExAnimOut
__kerjmp_HuWinExAnimOut:
	b _HuWinExAnimOut
	.globl __kerjmp_HuWinExCleanup
__kerjmp_HuWinExCleanup:
	b _HuWinExCleanup
	.globl __kerjmp_HuWinExAnimPopIn
__kerjmp_HuWinExAnimPopIn:
	b _HuWinExAnimPopIn
	.globl __kerjmp_HuWinComKeyWait
__kerjmp_HuWinComKeyWait:
	b _HuWinComKeyWait
	.globl __kerjmp_HuWinComKeySet
__kerjmp_HuWinComKeySet:
	b _HuWinComKeySet
	.globl __kerjmp_HuWinComKeyReset
__kerjmp_HuWinComKeyReset:
	b _HuWinComKeyReset
	.globl __kerjmp_HuWinDrawNoSet
__kerjmp_HuWinDrawNoSet:
	b _HuWinDrawNoSet
	.globl __kerjmp_HuWinAttrSet
__kerjmp_HuWinAttrSet:
	b _HuWinAttrSet
	.globl __kerjmp_HuWinAttrReset
__kerjmp_HuWinAttrReset:
	b _HuWinAttrReset
	.globl __kerjmp_HuWinBGTPLvlSet
__kerjmp_HuWinBGTPLvlSet:
	b _HuWinBGTPLvlSet
	.globl __kerjmp_HuWinMesSpeedSet
__kerjmp_HuWinMesSpeedSet:
	b _HuWinMesSpeedSet
	.globl __kerjmp_HuWinBGColSet
__kerjmp_HuWinBGColSet:
	b _HuWinBGColSet
	.globl __kerjmp_HuWinChoiceDisable
__kerjmp_HuWinChoiceDisable:
	b _HuWinChoiceDisable
	.globl __kerjmp_HuWinKeyWaitEntry
__kerjmp_HuWinKeyWaitEntry:
	b _HuWinKeyWaitEntry
	.globl __kerjmp_HuWinCenterPosSet
__kerjmp_HuWinCenterPosSet:
	b _HuWinCenterPosSet
	.globl __kerjmp_HuWinPosSet
__kerjmp_HuWinPosSet:
	b _HuWinPosSet
	.globl __kerjmp_HuWinZRotSet
__kerjmp_HuWinZRotSet:
	b _HuWinZRotSet
	.globl __kerjmp_HuWinScaleSet
__kerjmp_HuWinScaleSet:
	b _HuWinScaleSet
	.globl __kerjmp_HuWinChoiceNowGet
__kerjmp_HuWinChoiceNowGet:
	b _HuWinChoiceNowGet
	.globl __kerjmp_HuWinStatGet
__kerjmp_HuWinStatGet:
	b _HuWinStatGet
	.globl __kerjmp_HuWinMesColSet
__kerjmp_HuWinMesColSet:
	b _HuWinMesColSet
	.globl __kerjmp_HuWinScissorSet
__kerjmp_HuWinScissorSet:
	b _HuWinScissorSet
	.globl __kerjmp_HuWinExCreateStyled
__kerjmp_HuWinExCreateStyled:
	b _HuWinExCreateStyled
	.globl __kerjmp_HuWinPriSet
__kerjmp_HuWinPriSet:
	b _HuWinPriSet
	.globl __kerjmp_HuWinSprPriSet
__kerjmp_HuWinSprPriSet:
	b _HuWinSprPriSet
	.globl __kerjmp_HuWinKeyWaitNumGet
__kerjmp_HuWinKeyWaitNumGet:
	b _HuWinKeyWaitNumGet
	.globl __kerjmp_HuWinMesSizeCancelCRSet
__kerjmp_HuWinMesSizeCancelCRSet:
	b _HuWinMesSizeCancelCRSet
	.globl __kerjmp_HuWinMesPalSet
__kerjmp_HuWinMesPalSet:
	b _HuWinMesPalSet
	.globl __kerjmp_HuWinHomeClear
__kerjmp_HuWinHomeClear:
	b _HuWinHomeClear
	.globl __kerjmp_HuWinPushKeySet
__kerjmp_HuWinPushKeySet:
	b _HuWinPushKeySet
	.globl __kerjmp_HuWinDisablePlayerSet
__kerjmp_HuWinDisablePlayerSet:
	b _HuWinDisablePlayerSet
	.globl __kerjmp_HuWinDisablePlayerReset
__kerjmp_HuWinDisablePlayerReset:
	b _HuWinDisablePlayerReset
	.globl __kerjmp_CharManInit
__kerjmp_CharManInit:
	b _CharInit
	.globl __kerjmp_CharMotionInit
__kerjmp_CharMotionInit:
	b _CharMotionInit
	.globl __kerjmp_CharDataClose
__kerjmp_CharDataClose:
	b _CharDataClose
	.globl __kerjmp_CharModelKill
__kerjmp_CharModelKill:
	b _CharModelKill
	.globl __kerjmp_CharClose
__kerjmp_CharClose:
	b _CharClose
	.globl __kerjmp_CharModelCreate
__kerjmp_CharModelCreate:
	b _CharModelCreate
	.globl __kerjmp_CharModelMotionCreate
__kerjmp_CharModelMotionCreate:
	b _CharMotionCreate
	.globl __kerjmp_CharModelMotionIndexSet
__kerjmp_CharModelMotionIndexSet:
	b _CharMotionNoSet
	.globl __kerjmp_CharModelMotionKill
__kerjmp_CharModelMotionKill:
	b _CharMotionKill
	.globl __kerjmp_CharModelMotionDataClose
__kerjmp_CharModelMotionDataClose:
	b _CharMotionDataClose
	.globl __kerjmp_CharModelDataClose
__kerjmp_CharModelDataClose:
	b _CharModelDataClose
	.globl __kerjmp_CharMotionAMemPGet
__kerjmp_CharMotionAMemPGet:
	b _CharMotionAMemPGet
	.globl __kerjmp_CharModelMotionSet
__kerjmp_CharModelMotionSet:
	b _CharMotionSet
	.globl __kerjmp_CharModelMotionTimeSet
__kerjmp_CharModelMotionTimeSet:
	b _CharMotionTimeSet
	.globl __kerjmp_CharModelMotionTimeGet
__kerjmp_CharModelMotionTimeGet:
	b _CharMotionTimeGet
	.globl __kerjmp_CharModelMotionMaxTimeGet
__kerjmp_CharModelMotionMaxTimeGet:
	b _CharMotionMaxTimeGet
	.globl __kerjmp_CharModelMotionEndCheck
__kerjmp_CharModelMotionEndCheck:
	b _CharMotionEndCheck
	.globl __kerjmp_CharModelMotionShiftIDGet
__kerjmp_CharModelMotionShiftIDGet:
	b _CharMotionShiftIDGet
	.globl __kerjmp_CharModelMotionShiftSet
__kerjmp_CharModelMotionShiftSet:
	b _CharMotionShiftSet
	.globl __kerjmp_CharModelMotionShiftTimeGet
__kerjmp_CharModelMotionShiftTimeGet:
	b _CharMotionShiftTimeGet
	.globl __kerjmp_CharModelMotionSpeedSet
__kerjmp_CharModelMotionSpeedSet:
	b _CharMotionSpeedSet
	.globl __kerjmp_CharModelLayerSetAll
__kerjmp_CharModelLayerSetAll:
	b _CharEffectLayerSet
	.globl __kerjmp_CharModelItemHookCreate
__kerjmp_CharModelItemHookCreate:
	b _CharModelHookDustCreate
	.globl __kerjmp_CharModelEffectCreate
__kerjmp_CharModelEffectCreate:
	b _CharEffectSmokeCreate
	.globl __kerjmp_CharModelCoinEffectCreate
__kerjmp_CharModelCoinEffectCreate:
	b _CharEffectCoinGlowCreate
	.globl __kerjmp_fn_8004EC74
__kerjmp_fn_8004EC74:
	b _CharModelHitCreate
	.globl __kerjmp_fn_8004EDA4
__kerjmp_fn_8004EDA4:
	b _CharEffectHitCreate
	.globl __kerjmp_fn_8004F13C
__kerjmp_fn_8004F13C:
	b _CharEffectShoeHitCreate
	.globl __kerjmp_fn_8004F058
__kerjmp_fn_8004F058:
	b _CharModelShoeHitCreate
	.globl __kerjmp_GWCharColorGet
__kerjmp_GWCharColorGet:
	b _GWCharColorGet
	.globl __kerjmp_CharModelLayerSetAll2
__kerjmp_CharModelLayerSetAll2:
	b _CharModelLayerSetAll2
	.globl __kerjmp_charTexNameTbl
__kerjmp_charTexNameTbl:
	b _charEyeBmpNameTbl
	.globl __kerjmp_CharModelTexNameGet
__kerjmp_CharModelTexNameGet:
	b _CharModelEyeBmpGet
	.globl __kerjmp_CharModelVoiceEnableSet
__kerjmp_CharModelVoiceEnableSet:
	b _CharMotionVoiceOnSet
	.globl __kerjmp_CharModelEffectNpcInitSilent
__kerjmp_CharModelEffectNpcInitSilent:
	b _CharNpcDustVoiceOffSet
	.globl __kerjmp_CharModelStepTypeSet
__kerjmp_CharModelStepTypeSet:
	b _CharModelStepFxSet
	.globl __kerjmp_fn_8004F52C
__kerjmp_fn_8004F52C:
	b _CharModelVoicePanAutoSet
	.globl __kerjmp_CharModelEffectEnableSet
__kerjmp_CharModelEffectEnableSet:
	b _CharModelFxFlagSet
	.globl __kerjmp_CharModelEffectNpcInit
__kerjmp_CharModelEffectNpcInit:
	b _CharNpcDustSet
	.globl __kerjmp_HuPrcSetStat
__kerjmp_HuPrcSetStat:
	b _HuPrcSetStat
	.globl __kerjmp_HuPrcResetStat
__kerjmp_HuPrcResetStat:
	b _HuPrcResetStat
	.globl __kerjmp_omGameSysInit
__kerjmp_omGameSysInit:
	b _omGameSysInit
	.globl __kerjmp_omResetStatBit
__kerjmp_omResetStatBit:
	b _omResetStatBit
	.globl __kerjmp_omCurrentOvlGet
__kerjmp_omCurrentOvlGet:
	b _omCurrentOvlGet
	.globl __kerjmp_omPauseChk
__kerjmp_omPauseChk:
	b _omPauseChk
	.globl __kerjmp_omOvlHisChg
__kerjmp_omOvlHisChg:
	b _omOvlHisChg
	.globl __kerjmp_omOvlHisGet
__kerjmp_omOvlHisGet:
	b _omOvlHisGet
	.globl __kerjmp_omovlevtno
__kerjmp_omovlevtno:
	b _omovlevtno
	.globl __kerjmp_omovlstat
__kerjmp_omovlstat:
	b _omovlstat
	.globl __kerjmp_AddX
__kerjmp_AddX:
	b _AddX
	.globl __kerjmp_AddZ
__kerjmp_AddZ:
	b _AddZ
	.globl __kerjmp_MapObject
__kerjmp_MapObject:
	b _MapObject
	.globl __kerjmp_CharObject
__kerjmp_CharObject:
	b _CharObject
	.globl __kerjmp_nMap
__kerjmp_nMap:
	b _nMap
	.globl __kerjmp_nChar
__kerjmp_nChar:
	b _nChar
	.globl __kerjmp_MapWall
__kerjmp_MapWall:
	b _MapWall
	.globl __kerjmp_MapPos
__kerjmp_MapPos:
	b _MapPos
	.globl __kerjmp_HitFaceVec
__kerjmp_HitFaceVec:
	b _HitFaceVec
	.globl __kerjmp_HitFace
__kerjmp_HitFace:
	b _HitFace
	.globl __kerjmp_HitFaceCount
__kerjmp_HitFaceCount:
	b _HitFaceCount
	.globl __kerjmp_GWPlayer
__kerjmp_GWPlayer:
	b _GWPlayer
	.globl __kerjmp_GWSystem
__kerjmp_GWSystem:
	b _GWSystem
	.globl __kerjmp_HuTHPSprCreateVol
__kerjmp_HuTHPSprCreateVol:
	b _HuTHPSprCreateVol
	.globl __kerjmp_HuTHPSprCreate
__kerjmp_HuTHPSprCreate:
	b _HuTHPSprCreate
	.globl __kerjmp_HuTHP3DCreateVol
__kerjmp_HuTHP3DCreateVol:
	b _HuTHP3DCreateVol
	.globl __kerjmp_HuTHP3DCreate
__kerjmp_HuTHP3DCreate:
	b _HuTHP3DCreate
	.globl __kerjmp_HuTHPStop
__kerjmp_HuTHPStop:
	b _HuTHPStop
	.globl __kerjmp_HuTHPClose
__kerjmp_HuTHPClose:
	b _HuTHPClose
	.globl __kerjmp_HuTHPRestart
__kerjmp_HuTHPRestart:
	b _HuTHPRestart
	.globl __kerjmp_HuTHPEndCheck
__kerjmp_HuTHPEndCheck:
	b _HuTHPEndCheck
	.globl __kerjmp_HuTHPFrameGet
__kerjmp_HuTHPFrameGet:
	b _HuTHPFrameGet
	.globl __kerjmp_HuTHPTotalFrameGet
__kerjmp_HuTHPTotalFrameGet:
	b _HuTHPTotalFrameGet
	.globl __kerjmp_HuTHPSetVolume
__kerjmp_HuTHPSetVolume:
	b _HuTHPSetVolume
	.globl __kerjmp_HuCardCheck
__kerjmp_HuCardCheck:
	b _HuCardCheck
	.globl __kerjmp_HuCardMount
__kerjmp_HuCardMount:
	b _HuCardMount
	.globl __kerjmp_HuCardFormat
__kerjmp_HuCardFormat:
	b _HuCardFormat
	.globl __kerjmp_HuCardOpen
__kerjmp_HuCardOpen:
	b _HuCardOpen
	.globl __kerjmp_HuCardRead
__kerjmp_HuCardRead:
	b _HuCardRead
	.globl __kerjmp_HuCardCreate
__kerjmp_HuCardCreate:
	b _HuCardCreate
	.globl __kerjmp_HuCardClose
__kerjmp_HuCardClose:
	b _HuCardClose
	.globl __kerjmp_HuCardWrite
__kerjmp_HuCardWrite:
	b _HuCardWrite
	.globl __kerjmp_HuCardDelete
__kerjmp_HuCardDelete:
	b _HuCardDelete
	.globl __kerjmp_HuCardSectorSizeGet
__kerjmp_HuCardSectorSizeGet:
	b _HuCardSectorSizeGet
	.globl __kerjmp_HuCardFreeSpaceGet
__kerjmp_HuCardFreeSpaceGet:
	b _HuCardFreeSpaceGet
	.globl __kerjmp_HuCardSlotCheck
__kerjmp_HuCardSlotCheck:
	b _HuCardSlotCheck
	.globl __kerjmp_SLFileOpen
__kerjmp_SLFileOpen:
	b _SLFileOpen
	.globl __kerjmp_SLFileCreate
__kerjmp_SLFileCreate:
	b _SLFileCreate
	.globl __kerjmp_SLFileWrite
__kerjmp_SLFileWrite:
	b _SLFileWrite
	.globl __kerjmp_SLFileClose
__kerjmp_SLFileClose:
	b _SLFileClose
	.globl __kerjmp_SLFileRead
__kerjmp_SLFileRead:
	b _SLFileRead
	.globl __kerjmp_SLCurSlotNoSet
__kerjmp_SLCurSlotNoSet:
	b _SLCurSlotNoSet
	.globl __kerjmp_SLSaveDataMake
__kerjmp_SLSaveDataMake:
	b _SLSaveDataMake
	.globl __kerjmp_SLCommonSet
__kerjmp_SLCommonSet:
	b _SLCommonSet
	.globl __kerjmp_SLSaveBoard
__kerjmp_SLSaveBoard:
	b _SLSaveBoard
	.globl __kerjmp_SLSaveBoardStory
__kerjmp_SLSaveBoardStory:
	b _SLSaveBoardStory
	.globl __kerjmp_SLSave
__kerjmp_SLSave:
	b _SLSave
	.globl __kerjmp_SLLoadGameStat
__kerjmp_SLLoadGameStat:
	b _SLLoadGameStat
	.globl __kerjmp_SLLoadBoard
__kerjmp_SLLoadBoard:
	b _SLLoadBoard
	.globl __kerjmp_SLLoadBoardStory
__kerjmp_SLLoadBoardStory:
	b _SLLoadBoardStory
	.globl __kerjmp_SLLoad
__kerjmp_SLLoad:
	b _SLLoad
	.globl __kerjmp_SLCurBoxNoSet
__kerjmp_SLCurBoxNoSet:
	b _SLCurBoxNoSet
	.globl __kerjmp_SLSaveFlagSet
__kerjmp_SLSaveFlagSet:
	b _SLSaveFlagSet
	.globl __kerjmp_SLSaveFlagGet
__kerjmp_SLSaveFlagGet:
	b _SLSaveFlagGet
	.globl __kerjmp_SLCheckSumCheck
__kerjmp_SLCheckSumCheck:
	b _SLCheckSumCheck
	.globl __kerjmp_SLSerialNoGet
__kerjmp_SLSerialNoGet:
	b _SLSerialNoGet
	.globl __kerjmp_SLSerialNoCheck
__kerjmp_SLSerialNoCheck:
	b _SLSerialNoCheck
	.globl __kerjmp_saveExecF
__kerjmp_saveExecF:
	b _saveExecF
	.globl __kerjmp__CheckFlag
__kerjmp__CheckFlag:
	b __CheckFlag
	.globl __kerjmp__SetFlag
__kerjmp__SetFlag:
	b __SetFlag
	.globl __kerjmp__ClearFlag
__kerjmp__ClearFlag:
	b __ClearFlag
	.globl __kerjmp_mgInfoTbl
__kerjmp_mgInfoTbl:
	b _mgInfoTbl
	.globl __kerjmp_mgTypeCurr
__kerjmp_mgTypeCurr:
	b _mgTypeCurr
	.globl __kerjmp_mgBattleStar
__kerjmp_mgBattleStar:
	b _mgBattleStar
	.globl __kerjmp_lbl_801D3E94_0
__kerjmp_lbl_801D3E94_0:
	b _lbl_801D3E94
	.globl __kerjmp_mgTicTacToeGrid
__kerjmp_mgTicTacToeGrid:
	b _mgTicTacToeGrid
	.globl __kerjmp_mgIndexList
__kerjmp_mgIndexList:
	b _mgIndexList
	.globl __kerjmp_lbl_801D3E94_1
__kerjmp_lbl_801D3E94_1:
	b _lbl_801D3E94
	.globl __kerjmp_mgGameStatBackup
__kerjmp_mgGameStatBackup:
	b _mgGameStatBackup
	.globl __kerjmp_mgRecordExtra
__kerjmp_mgRecordExtra:
	b _mgRecordExtra
	.globl __kerjmp_mgQuitExtraF
__kerjmp_mgQuitExtraF:
	b _mgQuitExtraF
	.globl __kerjmp_mgPracticeEnableF
__kerjmp_mgPracticeEnableF:
	b _mgPracticeEnableF
	.globl __kerjmp_mgBoardHostEnableF
__kerjmp_mgBoardHostEnableF:
	b _mgBoardHostEnableF
	.globl __kerjmp_omMgIndexGet
__kerjmp_omMgIndexGet:
	b _omMgIndexGet
	.globl __kerjmp_mgInstExitEnableF
__kerjmp_mgInstExitEnableF:
	b _mgInstExitEnableF
	.globl __kerjmp_GWMGRecordSet
__kerjmp_GWMGRecordSet:
	b _GWMGRecordSet
	.globl __kerjmp_GWMGRecordGet
__kerjmp_GWMGRecordGet:
	b _GWMGRecordGet
	.globl __kerjmp_GWBoardPlayCountAdd
__kerjmp_GWBoardPlayCountAdd:
	b _GWBoardPlayCountAdd
	.globl __kerjmp_GWBoardPlayCountSet
__kerjmp_GWBoardPlayCountSet:
	b _GWBoardPlayCountSet
	.globl __kerjmp_GWBoardPlayCountGet
__kerjmp_GWBoardPlayCountGet:
	b _GWBoardPlayCountGet
	.globl __kerjmp_GWBoardWinCountInc
__kerjmp_GWBoardWinCountInc:
	b _GWBoardWinCountInc
	.globl __kerjmp_GWBoardWinCountGet
__kerjmp_GWBoardWinCountGet:
	b _GWBoardWinCountGet
	.globl __kerjmp_GWBoardWinCountSet
__kerjmp_GWBoardWinCountSet:
	b _GWBoardWinCountSet
	.globl __kerjmp_GWBoardMaxStarsSet
__kerjmp_GWBoardMaxStarsSet:
	b _GWBoardMaxStarsSet
	.globl __kerjmp_GWBoardMaxStarsGet
__kerjmp_GWBoardMaxStarsGet:
	b _GWBoardMaxStarsGet
	.globl __kerjmp_GWBoardMaxCoinsSet
__kerjmp_GWBoardMaxCoinsSet:
	b _GWBoardMaxCoinsSet
	.globl __kerjmp_GWBoardMaxCoinsGet
__kerjmp_GWBoardMaxCoinsGet:
	b _GWBoardMaxCoinsGet
	.globl __kerjmp_GWTotalStarsSet
__kerjmp_GWTotalStarsSet:
	b _GWTotalStarsSet
	.globl __kerjmp_GWTotalStarsAdd
__kerjmp_GWTotalStarsAdd:
	b _GWTotalStarsAdd
	.globl __kerjmp_GWTotalStarsGet
__kerjmp_GWTotalStarsGet:
	b _GWTotalStarsGet
	.globl __kerjmp_GWStarsAdd
__kerjmp_GWStarsAdd:
	b _GWStarsAdd
	.globl __kerjmp_GWStarsGet
__kerjmp_GWStarsGet:
	b _GWStarsGet
	.globl __kerjmp_GWStarsSet
__kerjmp_GWStarsSet:
	b _GWStarsSet
	.globl __kerjmp_GWCoinsAdd
__kerjmp_GWCoinsAdd:
	b _GWCoinsAdd
	.globl __kerjmp_GWCoinsSet
__kerjmp_GWCoinsSet:
	b _GWCoinsSet
	.globl __kerjmp_GWCoinsGet
__kerjmp_GWCoinsGet:
	b _GWCoinsGet
	.globl __kerjmp_GWMGCustomReset
__kerjmp_GWMGCustomReset:
	b _GWMGCustomReset
	.globl __kerjmp_GWMGCustomSet
__kerjmp_GWMGCustomSet:
	b _GWMGCustomSet
	.globl __kerjmp_GWMGCustomGet
__kerjmp_GWMGCustomGet:
	b _GWMGCustomGet
	.globl __kerjmp_GWMGAvailGet
__kerjmp_GWMGAvailGet:
	b _GWMGAvailGet
	.globl __kerjmp_fmod
__kerjmp_fmod:
	b _fmod
	.globl __kerjmp_omDBGMenuButton
__kerjmp_omDBGMenuButton:
	b _omDBGMenuButton
	.globl __kerjmp_msmSeSetListener
__kerjmp_msmSeSetListener:
	b _msmSeSetListener
	.globl __kerjmp_msmSeUpdataListener
__kerjmp_msmSeUpdataListener:
	b _msmSeUpdataListener
	.globl __kerjmp_msmSeGetIndexPtr
__kerjmp_msmSeGetIndexPtr:
	b _msmSeGetIndexPtr
	.globl __kerjmp_msmMusSetMasterVolume
__kerjmp_msmMusSetMasterVolume:
	b _msmMusSetMasterVolume
	.globl __kerjmp_msmSysGetOutputMode
__kerjmp_msmSysGetOutputMode:
	b _msmSysGetOutputMode
	.globl __kerjmp_BoardRollExec
__kerjmp_BoardRollExec:
	b _BoardRollExec
	.globl __kerjmp_BoardRollKill
__kerjmp_BoardRollKill:
	b _BoardRollKill
	.globl __kerjmp_BoardDiceValueSet
__kerjmp_BoardDiceValueSet:
	b _BoardDiceValueSet
	.globl __kerjmp_BoardDiceStop
__kerjmp_BoardDiceStop:
	b _BoardDiceStop
	.globl __kerjmp_BoardDicePauseAll
__kerjmp_BoardDicePauseAll:
	b _BoardDicePauseAll
	.globl __kerjmp_BoardDiceDoneCheck
__kerjmp_BoardDiceDoneCheck:
	b _BoardDiceDoneCheck
	.globl __kerjmp_BoardObjectSetup
__kerjmp_BoardObjectSetup:
	b _BoardObjectSetup
	.globl __kerjmp_BoardStoryConfigSet
__kerjmp_BoardStoryConfigSet:
	b _BoardStoryConfigSet
	.globl __kerjmp_BoardPartyConfigSet
__kerjmp_BoardPartyConfigSet:
	b _BoardPartyConfigSet
	.globl __kerjmp_BoardSaveInit
__kerjmp_BoardSaveInit:
	b _BoardSaveInit
	.globl __kerjmp_BoardMGExit
__kerjmp_BoardMGExit:
	b _BoardMGExit
	.globl __kerjmp_BoardDAngleCalcVec
__kerjmp_BoardDAngleCalcVec:
	b _BoardDAngleCalcVec
	.globl __kerjmp_BoardDAngleCalc
__kerjmp_BoardDAngleCalc:
	b _BoardDAngleCalc
	.globl __kerjmp_BoardVecMaxDistXZCheck
__kerjmp_BoardVecMaxDistXZCheck:
	b _BoardVecMaxDistXZCheck
	.globl __kerjmp_BoardIsKill
__kerjmp_BoardIsKill:
	b _BoardIsKill
	.globl __kerjmp_BoardKill
__kerjmp_BoardKill:
	b _BoardKill
	.globl __kerjmp_BoardCameraScissorSet
__kerjmp_BoardCameraScissorSet:
	b _BoardCameraScissorSet
	.globl __kerjmp_BoardCameraViewSet
__kerjmp_BoardCameraViewSet:
	b _BoardCameraViewSet
	.globl __kerjmp_BoardCameraDirGet
__kerjmp_BoardCameraDirGet:
	b _BoardCameraDirGet
	.globl __kerjmp_BoardCameraPointDirGet
__kerjmp_BoardCameraPointDirGet:
	b _BoardCameraPointDirGet
	.globl __kerjmp_BoardCameraMoveSet
__kerjmp_BoardCameraMoveSet:
	b _BoardCameraMoveSet
	.globl __kerjmp_BoardCameraQuakeSet
__kerjmp_BoardCameraQuakeSet:
	b _BoardCameraQuakeSet
	.globl __kerjmp_BoardCameraQuakeReset
__kerjmp_BoardCameraQuakeReset:
	b _BoardCameraQuakeReset
	.globl __kerjmp_BoardCameraTargetSet
__kerjmp_BoardCameraTargetSet:
	b _BoardCameraTargetSet
	.globl __kerjmp_BoardCameraPosGet
__kerjmp_BoardCameraPosGet:
	b _BoardCameraPosGet
	.globl __kerjmp_BoardCameraTargetGet
__kerjmp_BoardCameraTargetGet:
	b _BoardCameraTargetGet
	.globl __kerjmp_BoardCameraRotGet
__kerjmp_BoardCameraRotGet:
	b _BoardCameraRotGet
	.globl __kerjmp_BoardCameraZoomGet
__kerjmp_BoardCameraZoomGet:
	b _BoardCameraZoomGet
	.globl __kerjmp_BoardCameraPosSet
__kerjmp_BoardCameraPosSet:
	b _BoardCameraPosSet
	.globl __kerjmp_BoardCameraXRotZoomSet
__kerjmp_BoardCameraXRotZoomSet:
	b _BoardCameraXRotZoomSet
	.globl __kerjmp_BoardCameraZoomSet
__kerjmp_BoardCameraZoomSet:
	b _BoardCameraZoomSet
	.globl __kerjmp_BoardCameraRotSet
__kerjmp_BoardCameraRotSet:
	b _BoardCameraRotSet
	.globl __kerjmp_BoardCameraFovSet
__kerjmp_BoardCameraFovSet:
	b _BoardCameraFovSet
	.globl __kerjmp_BoardCameraOffsetSet
__kerjmp_BoardCameraOffsetSet:
	b _BoardCameraOffsetSet
	.globl __kerjmp_BoardCameraTargetPlayerSet
__kerjmp_BoardCameraTargetPlayerSet:
	b _BoardCameraTargetPlayerSet
	.globl __kerjmp_BoardCameraTargetModelSet
__kerjmp_BoardCameraTargetModelSet:
	b _BoardCameraTargetModelSet
	.globl __kerjmp_BoardCameraTargetSpaceSet
__kerjmp_BoardCameraTargetSpaceSet:
	b _BoardCameraTargetSpaceSet
	.globl __kerjmp_BoardCameraCullCheck
__kerjmp_BoardCameraCullCheck:
	b _BoardCameraCullCheck
	.globl __kerjmp_BoardCameraMotionIsDone
__kerjmp_BoardCameraMotionIsDone:
	b _BoardCameraMotionIsDone
	.globl __kerjmp_BoardCameraMotionStartEx
__kerjmp_BoardCameraMotionStartEx:
	b _BoardCameraMotionStartEx
	.globl __kerjmp_BoardCameraMotionStart
__kerjmp_BoardCameraMotionStart:
	b _BoardCameraMotionStart
	.globl __kerjmp_BoardCameraMotionWait
__kerjmp_BoardCameraMotionWait:
	b _BoardCameraMotionWait
	.globl __kerjmp_BoardCameraNearFarSet
__kerjmp_BoardCameraNearFarSet:
	b _BoardCameraNearFarSet
	.globl __kerjmp_BoardCameraNearFarGet
__kerjmp_BoardCameraNearFarGet:
	b _BoardCameraNearFarGet
	.globl __kerjmp_BoardEventFlagSet
__kerjmp_BoardEventFlagSet:
	b _BoardEventFlagSet
	.globl __kerjmp_BoardEventFlagReset
__kerjmp_BoardEventFlagReset:
	b _BoardEventFlagReset
	.globl __kerjmp_BoardEventFlagGet
__kerjmp_BoardEventFlagGet:
	b _BoardEventFlagGet
	.globl __kerjmp_BoardMGCreate
__kerjmp_BoardMGCreate:
	b _BoardMGCreate
	.globl __kerjmp_BoardDAngleCalcRange
__kerjmp_BoardDAngleCalcRange:
	b _BoardDAngleCalcRange
	.globl __kerjmp_BoardVecDistXZCalc
__kerjmp_BoardVecDistXZCalc:
	b _BoardVecDistXZCalc
	.globl __kerjmp_BoardVecMinDistCheck
__kerjmp_BoardVecMinDistCheck:
	b _BoardVecMinDistCheck
	.globl __kerjmp_BoardArcSin
__kerjmp_BoardArcSin:
	b _BoardArcSin
	.globl __kerjmp_BoardArcCos
__kerjmp_BoardArcCos:
	b _BoardArcCos
	.globl __kerjmp_BoardMTXCalcLookAt
__kerjmp_BoardMTXCalcLookAt:
	b _BoardMTXCalcLookAt
	.globl __kerjmp_BoardLightSetExec
__kerjmp_BoardLightSetExec:
	b _BoardLightSetExec
	.globl __kerjmp_BoardLightResetExec
__kerjmp_BoardLightResetExec:
	b _BoardLightResetExec
	.globl __kerjmp_BoardLightHookSet
__kerjmp_BoardLightHookSet:
	b _BoardLightHookSet
	.globl __kerjmp_BoardMGDoneFlagSet
__kerjmp_BoardMGDoneFlagSet:
	b _BoardMGDoneFlagSet
	.globl __kerjmp_BoardMGDoneFlagGet
__kerjmp_BoardMGDoneFlagGet:
	b _BoardMGDoneFlagGet
	.globl __kerjmp_BoardMGSetupExec
__kerjmp_BoardMGSetupExec:
	b _BoardMGSetupExec
	.globl __kerjmp_BoardFilterFadeOut
__kerjmp_BoardFilterFadeOut:
	b _BoardFilterFadeOut
	.globl __kerjmp_BoardFilterFadeInit
__kerjmp_BoardFilterFadeInit:
	b _BoardFilterFadeInit
	.globl __kerjmp_BoardFilterFadePauseCheck
__kerjmp_BoardFilterFadePauseCheck:
	b _BoardFilterFadePauseCheck
	.globl __kerjmp_BoardFilterFadeCheck
__kerjmp_BoardFilterFadeCheck:
	b _BoardFilterFadeCheck
	.globl __kerjmp_BoardConfettiCreate
__kerjmp_BoardConfettiCreate:
	b _BoardConfettiCreate
	.globl __kerjmp_BoardConfettiKill
__kerjmp_BoardConfettiKill:
	b _BoardConfettiKill
	.globl __kerjmp_BoardConfettiStop
__kerjmp_BoardConfettiStop:
	b _BoardConfettiStop
	.globl __kerjmp_BoardRand
__kerjmp_BoardRand:
	b _BoardRand
	.globl __kerjmp_BoardRandMod
__kerjmp_BoardRandMod:
	b _BoardRandMod
	.globl __kerjmp_BoardRandFloat
__kerjmp_BoardRandFloat:
	b _BoardRandFloat
	.globl __kerjmp_boardRandSeed
__kerjmp_boardRandSeed:
	b _boardRandSeed
	.globl __kerjmp_BoardViewMoveCheck
__kerjmp_BoardViewMoveCheck:
	b _BoardViewMoveCheck
	.globl __kerjmp_BoardViewMoveEnd
__kerjmp_BoardViewMoveEnd:
	b _BoardViewMoveEnd
	.globl __kerjmp_BoardViewFocusGetPos
__kerjmp_BoardViewFocusGetPos:
	b _BoardViewFocusGetPos
	.globl __kerjmp_BoardViewMoveStart
__kerjmp_BoardViewMoveStart:
	b _BoardViewMoveStart
	.globl __kerjmp_BoardViewFocusSet
__kerjmp_BoardViewFocusSet:
	b _BoardViewFocusSet
	.globl __kerjmp_boardTurnFunc
__kerjmp_boardTurnFunc:
	b _boardTurnFunc
	.globl __kerjmp_boardStarShowNextHook
__kerjmp_boardStarShowNextHook:
	b _boardStarShowNextHook
	.globl __kerjmp_boardBowserHook
__kerjmp_boardBowserHook:
	b _boardBowserHook
	.globl __kerjmp_boardTurnStartFunc
__kerjmp_boardTurnStartFunc:
	b _boardTurnStartFunc
	.globl __kerjmp_boardStarGiveHook
__kerjmp_boardStarGiveHook:
	b _boardStarGiveHook
	.globl __kerjmp_boardMainProc
__kerjmp_boardMainProc:
	b _boardMainProc
	.globl __kerjmp_boardObjMan
__kerjmp_boardObjMan:
	b _boardObjMan
	.globl __kerjmp_BoardItemStart
__kerjmp_BoardItemStart:
	b _BoardItemStart
	.globl __kerjmp_BoardCharWheelInit
__kerjmp_BoardCharWheelInit:
	b _BoardCharWheelInit
	.globl __kerjmp_BoardCharWheelCheck
__kerjmp_BoardCharWheelCheck:
	b _BoardCharWheelCheck
	.globl __kerjmp_BoardCharWheelWait
__kerjmp_BoardCharWheelWait:
	b _BoardCharWheelWait
	.globl __kerjmp_BoardCharWheelResultGet
__kerjmp_BoardCharWheelResultGet:
	b _BoardCharWheelResultGet
	.globl __kerjmp_BoardCharWheelSpeedSet
__kerjmp_BoardCharWheelSpeedSet:
	b _BoardCharWheelSpeedSet
	.globl __kerjmp_BoardSpaceInit
__kerjmp_BoardSpaceInit:
	b _BoardSpaceInit
	.globl __kerjmp_BoardSpaceDestroy
__kerjmp_BoardSpaceDestroy:
	b _BoardSpaceDestroy
	.globl __kerjmp_BoardSpaceLandExec
__kerjmp_BoardSpaceLandExec:
	b _BoardSpaceLandExec
	.globl __kerjmp_BoardSpaceWalkEventFuncSet
__kerjmp_BoardSpaceWalkEventFuncSet:
	b _BoardSpaceWalkEventFuncSet
	.globl __kerjmp_BoardSpaceWalkMiniEventFuncSet
__kerjmp_BoardSpaceWalkMiniEventFuncSet:
	b _BoardSpaceWalkMiniEventFuncSet
	.globl __kerjmp_BoardSpaceLandEventFuncSet
__kerjmp_BoardSpaceLandEventFuncSet:
	b _BoardSpaceLandEventFuncSet
	.globl __kerjmp_BoardSpaceWalkEventExec
__kerjmp_BoardSpaceWalkEventExec:
	b _BoardSpaceWalkEventExec
	.globl __kerjmp_BoardSpaceWalkMiniEventExec
__kerjmp_BoardSpaceWalkMiniEventExec:
	b _BoardSpaceWalkMiniEventExec
	.globl __kerjmp_BoardSpaceBlockExec
__kerjmp_BoardSpaceBlockExec:
	b _BoardSpaceBlockExec
	.globl __kerjmp_BoardSpaceWalkExec
__kerjmp_BoardSpaceWalkExec:
	b _BoardSpaceWalkExec
	.globl __kerjmp_BoardSpaceCameraSet
__kerjmp_BoardSpaceCameraSet:
	b _BoardSpaceCameraSet
	.globl __kerjmp_BoardSpaceCornerPosGet
__kerjmp_BoardSpaceCornerPosGet:
	b _BoardSpaceCornerPosGet
	.globl __kerjmp_BoardSpaceStarGetRandom
__kerjmp_BoardSpaceStarGetRandom:
	b _BoardSpaceStarGetRandom
	.globl __kerjmp_BoardSpaceCountGet
__kerjmp_BoardSpaceCountGet:
	b _BoardSpaceCountGet
	.globl __kerjmp_BoardSpaceGet
__kerjmp_BoardSpaceGet:
	b _BoardSpaceGet
	.globl __kerjmp_BoardSpaceFlagPosGet
__kerjmp_BoardSpaceFlagPosGet:
	b _BoardSpaceFlagPosGet
	.globl __kerjmp_BoardSpaceFlagGet
__kerjmp_BoardSpaceFlagGet:
	b _BoardSpaceFlagGet
	.globl __kerjmp_BoardSpaceLinkTypeSearch
__kerjmp_BoardSpaceLinkTypeSearch:
	b _BoardSpaceLinkTypeSearch
	.globl __kerjmp_BoardSpacePosGet
__kerjmp_BoardSpacePosGet:
	b _BoardSpacePosGet
	.globl __kerjmp_BoardSpaceRotGet
__kerjmp_BoardSpaceRotGet:
	b _BoardSpaceRotGet
	.globl __kerjmp_BoardSpaceRead
__kerjmp_BoardSpaceRead:
	b _BoardSpaceRead
	.globl __kerjmp_BoardSpaceAttrReset
__kerjmp_BoardSpaceAttrReset:
	b _BoardSpaceAttrReset
	.globl __kerjmp_BoardSpaceAttrSet
__kerjmp_BoardSpaceAttrSet:
	b _BoardSpaceAttrSet
	.globl __kerjmp_BoardSpaceLinkTargetListGet
__kerjmp_BoardSpaceLinkTargetListGet:
	b _BoardSpaceLinkTargetListGet
	.globl __kerjmp_BoardSpaceFlagSearch
__kerjmp_BoardSpaceFlagSearch:
	b _BoardSpaceFlagSearch
	.globl __kerjmp_BoardSpaceTypeGet
__kerjmp_BoardSpaceTypeGet:
	b _BoardSpaceTypeGet
	.globl __kerjmp_BoardSpaceTypeSet
__kerjmp_BoardSpaceTypeSet:
	b _BoardSpaceTypeSet
	.globl __kerjmp_BoardSpaceLinkFlagSearch
__kerjmp_BoardSpaceLinkFlagSearch:
	b _BoardSpaceLinkFlagSearch
	.globl __kerjmp_BoardSpaceLinkTypeListGet
__kerjmp_BoardSpaceLinkTypeListGet:
	b _BoardSpaceLinkTypeListGet
	.globl __kerjmp_BoardSpaceLinkTransformGet
__kerjmp_BoardSpaceLinkTransformGet:
	b _BoardSpaceLinkTransformGet
	.globl __kerjmp_BoardSpaceHide
__kerjmp_BoardSpaceHide:
	b _BoardSpaceHide
	.globl __kerjmp_BoardSpaceStarCheck
__kerjmp_BoardSpaceStarCheck:
	b _BoardSpaceStarCheck
	.globl __kerjmp_BoardSpaceStarMove
__kerjmp_BoardSpaceStarMove:
	b _BoardSpaceStarMove
	.globl __kerjmp_BoardSpaceStarSetIndex
__kerjmp_BoardSpaceStarSetIndex:
	b _BoardSpaceStarSetIndex
	.globl __kerjmp_BoardSpaceStarGetCurr
__kerjmp_BoardSpaceStarGetCurr:
	b _BoardSpaceStarGetCurr
	.globl __kerjmp_BoardSpaceStarGet
__kerjmp_BoardSpaceStarGet:
	b _BoardSpaceStarGet
	.globl __kerjmp_BoardStarHostSet
__kerjmp_BoardStarHostSet:
	b _BoardStarHostSet
	.globl __kerjmp_BoardStarHostMdlGet
__kerjmp_BoardStarHostMdlGet:
	b _BoardStarHostMdlGet
	.globl __kerjmp_BoardBooHouseHostSet
__kerjmp_BoardBooHouseHostSet:
	b _BoardBooHouseHostSet
	.globl __kerjmp_BoardBooHouseHostGet
__kerjmp_BoardBooHouseHostGet:
	b _BoardBooHouseHostGet
	.globl __kerjmp_BoardLotteryHostSet
__kerjmp_BoardLotteryHostSet:
	b _BoardLotteryHostSet
	.globl __kerjmp_BoardLotteryHostGet
__kerjmp_BoardLotteryHostGet:
	b _BoardLotteryHostGet
	.globl __kerjmp_BoardShopHostSet
__kerjmp_BoardShopHostSet:
	b _BoardShopHostSet
	.globl __kerjmp_BoardShopHostGet
__kerjmp_BoardShopHostGet:
	b _BoardShopHostGet
	.globl __kerjmp_BoardPauseActiveCheck
__kerjmp_BoardPauseActiveCheck:
	b _BoardPauseActiveCheck
	.globl __kerjmp_BoardLotteryInit
__kerjmp_BoardLotteryInit:
	b _BoardLotteryInit
	.globl __kerjmp_BoardLotteryKill
__kerjmp_BoardLotteryKill:
	b _BoardLotteryKill
	.globl __kerjmp_BoardLotteryExec
__kerjmp_BoardLotteryExec:
	b _BoardLotteryExec
	.globl __kerjmp_BoardBooHouseCreate
__kerjmp_BoardBooHouseCreate:
	b _BoardBooHouseCreate
	.globl __kerjmp_BoardBooHouseKill
__kerjmp_BoardBooHouseKill:
	b _BoardBooHouseKill
	.globl __kerjmp_BoardBooHouseExec
__kerjmp_BoardBooHouseExec:
	b _BoardBooHouseExec
	.globl __kerjmp_BoardLandBlueExec
__kerjmp_BoardLandBlueExec:
	b _BoardLandBlueExec
	.globl __kerjmp_BoardLandRedExec
__kerjmp_BoardLandRedExec:
	b _BoardLandRedExec
	.globl __kerjmp_BoardWarpExec
__kerjmp_BoardWarpExec:
	b _BoardWarpExec
	.globl __kerjmp_BoardMushroomExec
__kerjmp_BoardMushroomExec:
	b _BoardMushroomExec
	.globl __kerjmp_BoardStarExec
__kerjmp_BoardStarExec:
	b _BoardStarExec
	.globl __kerjmp_BoardStarGive
__kerjmp_BoardStarGive:
	b _BoardStarGive
	.globl __kerjmp_BoardBattleExec
__kerjmp_BoardBattleExec:
	b _BoardBattleExec
	.globl __kerjmp_BoardShopInit
__kerjmp_BoardShopInit:
	b _BoardShopInit
	.globl __kerjmp_BoardShopKill
__kerjmp_BoardShopKill:
	b _BoardShopKill
	.globl __kerjmp_BoardShopExec
__kerjmp_BoardShopExec:
	b _BoardShopExec
	.globl __kerjmp_BoardModelInit
__kerjmp_BoardModelInit:
	b _BoardModelInit
	.globl __kerjmp_BoardModelKillAll
__kerjmp_BoardModelKillAll:
	b _BoardModelKillAll
	.globl __kerjmp_BoardModelDummyUpdate
__kerjmp_BoardModelDummyUpdate:
	b _BoardModelDummyUpdate
	.globl __kerjmp_BoardModelVisibilityUpdate
__kerjmp_BoardModelVisibilityUpdate:
	b _BoardModelVisibilityUpdate
	.globl __kerjmp_BoardModelKill
__kerjmp_BoardModelKill:
	b _BoardModelKill
	.globl __kerjmp_BoardModelExistCheck
__kerjmp_BoardModelExistCheck:
	b _BoardModelExistCheck
	.globl __kerjmp_BoardModelExistDupe
__kerjmp_BoardModelExistDupe:
	b _BoardModelExistDupe
	.globl __kerjmp_BoardModelIDGet
__kerjmp_BoardModelIDGet:
	b _BoardModelIDGet
	.globl __kerjmp_BoardModelAlphaSet
__kerjmp_BoardModelAlphaSet:
	b _BoardModelAlphaSet
	.globl __kerjmp_BoardModelMotionStart
__kerjmp_BoardModelMotionStart:
	b _BoardModelMotionStart
	.globl __kerjmp_BoardModelMotionShiftSet
__kerjmp_BoardModelMotionShiftSet:
	b _BoardModelMotionShiftSet
	.globl __kerjmp_BoardModelAttrSet
__kerjmp_BoardModelAttrSet:
	b _BoardModelAttrSet
	.globl __kerjmp_BoardModelAttrReset
__kerjmp_BoardModelAttrReset:
	b _BoardModelAttrReset
	.globl __kerjmp_BoardModelMotionTimeSet
__kerjmp_BoardModelMotionTimeSet:
	b _BoardModelMotionTimeSet
	.globl __kerjmp_BoardModelMotionSpeedSet
__kerjmp_BoardModelMotionSpeedSet:
	b _BoardModelMotionSpeedSet
	.globl __kerjmp_BoardModelMotionSpeedGet
__kerjmp_BoardModelMotionSpeedGet:
	b _BoardModelMotionSpeedGet
	.globl __kerjmp_BoardModelMotionStartEndSet
__kerjmp_BoardModelMotionStartEndSet:
	b _BoardModelMotionStartEndSet
	.globl __kerjmp_BoardModelMotionUpdateSet
__kerjmp_BoardModelMotionUpdateSet:
	b _BoardModelMotionUpdateSet
	.globl __kerjmp_BoardModelMotionShapeSet
__kerjmp_BoardModelMotionShapeSet:
	b _BoardModelMotionShapeSet
	.globl __kerjmp_BoardModelMotionShapeTimeGet
__kerjmp_BoardModelMotionShapeTimeGet:
	b _BoardModelMotionShapeTimeGet
	.globl __kerjmp_BoardModelMotionShapeMaxTimeGet
__kerjmp_BoardModelMotionShapeMaxTimeGet:
	b _BoardModelMotionShapeMaxTimeGet
	.globl __kerjmp_BoardModelMotionShapeSpeedSet
__kerjmp_BoardModelMotionShapeSpeedSet:
	b _BoardModelMotionShapeSpeedSet
	.globl __kerjmp_BoardModelMotionShapeSpeedGet
__kerjmp_BoardModelMotionShapeSpeedGet:
	b _BoardModelMotionShapeSpeedGet
	.globl __kerjmp_BoardModelMotionShapeEndCheck
__kerjmp_BoardModelMotionShapeEndCheck:
	b _BoardModelMotionShapeEndCheck
	.globl __kerjmp_BoardModelMotionShapeStartEndSet
__kerjmp_BoardModelMotionShapeStartEndSet:
	b _BoardModelMotionShapeStartEndSet
	.globl __kerjmp_BoardModelMtxSet
__kerjmp_BoardModelMtxSet:
	b _BoardModelMtxSet
	.globl __kerjmp_BoardModelMtxGet
__kerjmp_BoardModelMtxGet:
	b _BoardModelMtxGet
	.globl __kerjmp_BoardModelPosSetV
__kerjmp_BoardModelPosSetV:
	b _BoardModelPosSetV
	.globl __kerjmp_BoardModelRotSetV
__kerjmp_BoardModelRotSetV:
	b _BoardModelRotSetV
	.globl __kerjmp_BoardModelScaleSetV
__kerjmp_BoardModelScaleSetV:
	b _BoardModelScaleSetV
	.globl __kerjmp_BoardModelPosSet
__kerjmp_BoardModelPosSet:
	b _BoardModelPosSet
	.globl __kerjmp_BoardModelRotSet
__kerjmp_BoardModelRotSet:
	b _BoardModelRotSet
	.globl __kerjmp_BoardModelScaleSet
__kerjmp_BoardModelScaleSet:
	b _BoardModelScaleSet
	.globl __kerjmp_BoardModelPosGet
__kerjmp_BoardModelPosGet:
	b _BoardModelPosGet
	.globl __kerjmp_BoardModelRotGet
__kerjmp_BoardModelRotGet:
	b _BoardModelRotGet
	.globl __kerjmp_BoardModelScaleGet
__kerjmp_BoardModelScaleGet:
	b _BoardModelScaleGet
	.globl __kerjmp_fn_8006DDE8
__kerjmp_fn_8006DDE8:
	b _fn_8006DDE8
	.globl __kerjmp_BoardModelVisibilitySet
__kerjmp_BoardModelVisibilitySet:
	b _BoardModelVisibilitySet
	.globl __kerjmp_BoardModelVisibilityGet
__kerjmp_BoardModelVisibilityGet:
	b _BoardModelVisibilityGet
	.globl __kerjmp_BoardModelLayerSet
__kerjmp_BoardModelLayerSet:
	b _BoardModelLayerSet
	.globl __kerjmp_BoardModelCameraSet
__kerjmp_BoardModelCameraSet:
	b _BoardModelCameraSet
	.globl __kerjmp_BoardModelPassSet
__kerjmp_BoardModelPassSet:
	b _BoardModelPassSet
	.globl __kerjmp_fn_8006DC1C
__kerjmp_fn_8006DC1C:
	b _fn_8006DC1C
	.globl __kerjmp_BoardModelHookSet
__kerjmp_BoardModelHookSet:
	b _BoardModelHookSet
	.globl __kerjmp_BoardModelHookReset
__kerjmp_BoardModelHookReset:
	b _BoardModelHookReset
	.globl __kerjmp_BoardModelHookObjReset
__kerjmp_BoardModelHookObjReset:
	b _BoardModelHookObjReset
	.globl __kerjmp_BoardModelMotionEndCheck
__kerjmp_BoardModelMotionEndCheck:
	b _BoardModelMotionEndCheck
	.globl __kerjmp_BoardModelMotionTimeGet
__kerjmp_BoardModelMotionTimeGet:
	b _BoardModelMotionTimeGet
	.globl __kerjmp_BoardModelMotionMaxTimeGet
__kerjmp_BoardModelMotionMaxTimeGet:
	b _BoardModelMotionMaxTimeGet
	.globl __kerjmp_BoardModelMotionCreate
__kerjmp_BoardModelMotionCreate:
	b _BoardModelMotionCreate
	.globl __kerjmp_BoardModelMotionKill
__kerjmp_BoardModelMotionKill:
	b _BoardModelMotionKill
	.globl __kerjmp_BoardModelCreate
__kerjmp_BoardModelCreate:
	b _BoardModelCreate
	.globl __kerjmp_BoardModelCreateCharacter
__kerjmp_BoardModelCreateCharacter:
	b _BoardModelCreateCharacter
	.globl __kerjmp_BoardModelCreateParam
__kerjmp_BoardModelCreateParam:
	b _BoardModelCreateParam
	.globl __kerjmp_BoardModelLayerSetAll
__kerjmp_BoardModelLayerSetAll:
	b _BoardModelLayerSetAll
	.globl __kerjmp_BoardModelCameraSetAll
__kerjmp_BoardModelCameraSetAll:
	b _BoardModelCameraSetAll
	.globl __kerjmp_BoardModelHideSetAll
__kerjmp_BoardModelHideSetAll:
	b _BoardModelHideSetAll
	.globl __kerjmp_BoardModelAmbSet
__kerjmp_BoardModelAmbSet:
	b _BoardModelAmbSet
	.globl __kerjmp_BoardModelAmbSetAll
__kerjmp_BoardModelAmbSetAll:
	b _BoardModelAmbSetAll
	.globl __kerjmp_BoardModelRotYSet
__kerjmp_BoardModelRotYSet:
	b _BoardModelRotYSet
	.globl __kerjmp_BoardModelRotYGet
__kerjmp_BoardModelRotYGet:
	b _BoardModelRotYGet
	.globl __kerjmp_BoardModelVoiceEnableSet
__kerjmp_BoardModelVoiceEnableSet:
	b _BoardModelVoiceEnableSet
	.globl __kerjmp_BoardPlayerModelInit
__kerjmp_BoardPlayerModelInit:
	b _BoardPlayerModelInit
	.globl __kerjmp_BoardPlayerModelKill
__kerjmp_BoardPlayerModelKill:
	b _BoardPlayerModelKill
	.globl __kerjmp_BoardPlayerInit
__kerjmp_BoardPlayerInit:
	b _BoardPlayerInit
	.globl __kerjmp_BoardPlayerGetCharMess
__kerjmp_BoardPlayerGetCharMess:
	b _BoardPlayerGetCharMess
	.globl __kerjmp_BoardPlayerGetCharName
__kerjmp_BoardPlayerGetCharName:
	b _BoardPlayerGetCharName
	.globl __kerjmp_BoardPlayerLayerSet
__kerjmp_BoardPlayerLayerSet:
	b _BoardPlayerLayerSet
	.globl __kerjmp_BoardPlayerCameraSet
__kerjmp_BoardPlayerCameraSet:
	b _BoardPlayerCameraSet
	.globl __kerjmp_fn_80062A40
__kerjmp_fn_80062A40:
	b _fn_80062A40
	.globl __kerjmp_BoardPlayerExistCheck
__kerjmp_BoardPlayerExistCheck:
	b _BoardPlayerExistCheck
	.globl __kerjmp_BoardPlayerMtxSet
__kerjmp_BoardPlayerMtxSet:
	b _BoardPlayerMtxSet
	.globl __kerjmp_BoardPlayerPosSet
__kerjmp_BoardPlayerPosSet:
	b _BoardPlayerPosSet
	.globl __kerjmp_BoardPlayerPosSetV
__kerjmp_BoardPlayerPosSetV:
	b _BoardPlayerPosSetV
	.globl __kerjmp_BoardPlayerPosGet
__kerjmp_BoardPlayerPosGet:
	b _BoardPlayerPosGet
	.globl __kerjmp_BoardPlayerRotSet
__kerjmp_BoardPlayerRotSet:
	b _BoardPlayerRotSet
	.globl __kerjmp_BoardPlayerRotSetV
__kerjmp_BoardPlayerRotSetV:
	b _BoardPlayerRotSetV
	.globl __kerjmp_BoardPlayerRotGet
__kerjmp_BoardPlayerRotGet:
	b _BoardPlayerRotGet
	.globl __kerjmp_BoardPlayerRotYSet
__kerjmp_BoardPlayerRotYSet:
	b _BoardPlayerRotYSet
	.globl __kerjmp_BoardPlayerRotYGet
__kerjmp_BoardPlayerRotYGet:
	b _BoardPlayerRotYGet
	.globl __kerjmp_BoardPlayerScaleSet
__kerjmp_BoardPlayerScaleSet:
	b _BoardPlayerScaleSet
	.globl __kerjmp_BoardPlayerScaleSetV
__kerjmp_BoardPlayerScaleSetV:
	b _BoardPlayerScaleSetV
	.globl __kerjmp_BoardPlayerScaleGet
__kerjmp_BoardPlayerScaleGet:
	b _BoardPlayerScaleGet
	.globl __kerjmp_BoardPlayerCornerPosSet
__kerjmp_BoardPlayerCornerPosSet:
	b _BoardPlayerCornerPosSet
	.globl __kerjmp_BoardPlayerCornerPosGet
__kerjmp_BoardPlayerCornerPosGet:
	b _BoardPlayerCornerPosGet
	.globl __kerjmp_BoardPlayerSizeGet
__kerjmp_BoardPlayerSizeGet:
	b _BoardPlayerSizeGet
	.globl __kerjmp_BoardPlayerSizeSet
__kerjmp_BoardPlayerSizeSet:
	b _BoardPlayerSizeSet
	.globl __kerjmp_BoardPlayerCurrMotionGet
__kerjmp_BoardPlayerCurrMotionGet:
	b _BoardPlayerCurrMotionGet
	.globl __kerjmp_BoardPlayerMotionEndCheck
__kerjmp_BoardPlayerMotionEndCheck:
	b _BoardPlayerMotionEndCheck
	.globl __kerjmp_BoardPlayerMotionEndWait
__kerjmp_BoardPlayerMotionEndWait:
	b _BoardPlayerMotionEndWait
	.globl __kerjmp_BoardPlayerMotionMaxTimeGet
__kerjmp_BoardPlayerMotionMaxTimeGet:
	b _BoardPlayerMotionMaxTimeGet
	.globl __kerjmp_BoardPlayerMotionTimeGet
__kerjmp_BoardPlayerMotionTimeGet:
	b _BoardPlayerMotionTimeGet
	.globl __kerjmp_BoardPlayerVoiceEnableSet
__kerjmp_BoardPlayerVoiceEnableSet:
	b _BoardPlayerVoiceEnableSet
	.globl __kerjmp_BoardPlayerMotionStart
__kerjmp_BoardPlayerMotionStart:
	b _BoardPlayerMotionStart
	.globl __kerjmp_BoardPlayerMotionShiftSet
__kerjmp_BoardPlayerMotionShiftSet:
	b _BoardPlayerMotionShiftSet
	.globl __kerjmp_BoardPlayerMotionCreate
__kerjmp_BoardPlayerMotionCreate:
	b _BoardPlayerMotionCreate
	.globl __kerjmp_BoardPlayerMotionKill
__kerjmp_BoardPlayerMotionKill:
	b _BoardPlayerMotionKill
	.globl __kerjmp_BoardPlayerMotionSpeedSet
__kerjmp_BoardPlayerMotionSpeedSet:
	b _BoardPlayerMotionSpeedSet
	.globl __kerjmp_BoardPlayerMotionTimeSet
__kerjmp_BoardPlayerMotionTimeSet:
	b _BoardPlayerMotionTimeSet
	.globl __kerjmp_BoardPlayerMotionStartEndSet
__kerjmp_BoardPlayerMotionStartEndSet:
	b _BoardPlayerMotionStartEndSet
	.globl __kerjmp_BoardPlayerModelAttrSet
__kerjmp_BoardPlayerModelAttrSet:
	b _BoardPlayerModelAttrSet
	.globl __kerjmp_BoardPlayerModelAttrReset
__kerjmp_BoardPlayerModelAttrReset:
	b _BoardPlayerModelAttrReset
	.globl __kerjmp_BoardPlayerAmbSet
__kerjmp_BoardPlayerAmbSet:
	b _BoardPlayerAmbSet
	.globl __kerjmp_BoardPlayerIdleSet
__kerjmp_BoardPlayerIdleSet:
	b _BoardPlayerIdleSet
	.globl __kerjmp_BoardPlayerMotBlendSet
__kerjmp_BoardPlayerMotBlendSet:
	b _BoardPlayerMotBlendSet
	.globl __kerjmp_BoardPlayerMotBlendCheck
__kerjmp_BoardPlayerMotBlendCheck:
	b _BoardPlayerMotBlendCheck
	.globl __kerjmp_BoardPlayerRankCalc
__kerjmp_BoardPlayerRankCalc:
	b _BoardPlayerRankCalc
	.globl __kerjmp_BoardItemPrevGet
__kerjmp_BoardItemPrevGet:
	b _BoardItemPrevGet
	.globl __kerjmp_BoardItemPrevSet
__kerjmp_BoardItemPrevSet:
	b _BoardItemPrevSet
	.globl __kerjmp_BoardPlayerItemRemove
__kerjmp_BoardPlayerItemRemove:
	b _BoardPlayerItemRemove
	.globl __kerjmp_BoardPlayerItemFind
__kerjmp_BoardPlayerItemFind:
	b _BoardPlayerItemFind
	.globl __kerjmp_BoardPlayerItemAdd
__kerjmp_BoardPlayerItemAdd:
	b _BoardPlayerItemAdd
	.globl __kerjmp_BoardPlayerItemCount
__kerjmp_BoardPlayerItemCount:
	b _BoardPlayerItemCount
	.globl __kerjmp_BoardPlayerCoinsAdd
__kerjmp_BoardPlayerCoinsAdd:
	b _BoardPlayerCoinsAdd
	.globl __kerjmp_BoardPlayerCoinsGet
__kerjmp_BoardPlayerCoinsGet:
	b _BoardPlayerCoinsGet
	.globl __kerjmp_BoardPlayerCoinsSet
__kerjmp_BoardPlayerCoinsSet:
	b _BoardPlayerCoinsSet
	.globl __kerjmp_BoardPlayerStarsAdd
__kerjmp_BoardPlayerStarsAdd:
	b _BoardPlayerStarsAdd
	.globl __kerjmp_BoardPlayerSameTeamFind
__kerjmp_BoardPlayerSameTeamFind:
	b _BoardPlayerSameTeamFind
	.globl __kerjmp_BoardPlayerPosLerpStart
__kerjmp_BoardPlayerPosLerpStart:
	b _BoardPlayerPosLerpStart
	.globl __kerjmp_BoardPlayerMoveToAsync
__kerjmp_BoardPlayerMoveToAsync:
	b _BoardPlayerMoveToAsync
	.globl __kerjmp_BoardPlayerDiceJumpStart
__kerjmp_BoardPlayerDiceJumpStart:
	b _BoardPlayerDiceJumpStart
	.globl __kerjmp_BoardPlayerDiceJumpCheck
__kerjmp_BoardPlayerDiceJumpCheck:
	b _BoardPlayerDiceJumpCheck
	.globl __kerjmp_BoardRollCreate
__kerjmp_BoardRollCreate:
	b _BoardRollCreate
	.globl __kerjmp_BoardRollUpdateSet
__kerjmp_BoardRollUpdateSet:
	b _BoardRollUpdateSet
	.globl __kerjmp_BoardRollDispSet
__kerjmp_BoardRollDispSet:
	b _BoardRollDispSet
	.globl __kerjmp_BoardPlayerBtnDownWait
__kerjmp_BoardPlayerBtnDownWait:
	b _BoardPlayerBtnDownWait
	.globl __kerjmp_BoardPlayerAutoSizeSet
__kerjmp_BoardPlayerAutoSizeSet:
	b _BoardPlayerAutoSizeSet
	.globl __kerjmp_BoardPlayerAutoSizeGet
__kerjmp_BoardPlayerAutoSizeGet:
	b _BoardPlayerAutoSizeGet
	.globl __kerjmp_BoardPlayerMoveAwayIsDone
__kerjmp_BoardPlayerMoveAwayIsDone:
	b _BoardPlayerMoveAwayIsDone
	.globl __kerjmp_BoardPlayerMoveAwayStartCurr
__kerjmp_BoardPlayerMoveAwayStartCurr:
	b _BoardPlayerMoveAwayStartCurr
	.globl __kerjmp_BoardPlayerMoveAwayStart
__kerjmp_BoardPlayerMoveAwayStart:
	b _BoardPlayerMoveAwayStart
	.globl __kerjmp_BoardPlayerPreTurnHookSet
__kerjmp_BoardPlayerPreTurnHookSet:
	b _BoardPlayerPreTurnHookSet
	.globl __kerjmp_BoardPlayerPostTurnHookSet
__kerjmp_BoardPlayerPostTurnHookSet:
	b _BoardPlayerPostTurnHookSet
	.globl __kerjmp_BoardPlayerCopyEyeMat
__kerjmp_BoardPlayerCopyEyeMat:
	b _BoardPlayerCopyEyeMat
	.globl __kerjmp_BoardBowserSuitInit
__kerjmp_BoardBowserSuitInit:
	b _BoardBowserSuitInit
	.globl __kerjmp_BoardBowserSuitKill
__kerjmp_BoardBowserSuitKill:
	b _BoardBowserSuitKill
	.globl __kerjmp_BoardBowserSuitModelGet
__kerjmp_BoardBowserSuitModelGet:
	b _BoardBowserSuitModelGet
	.globl __kerjmp_BoardBowserSuitPlayerModelGet
__kerjmp_BoardBowserSuitPlayerModelGet:
	b _BoardBowserSuitPlayerModelGet
	.globl __kerjmp_BoardBowserSuitPlayerModelKill
__kerjmp_BoardBowserSuitPlayerModelKill:
	b _BoardBowserSuitPlayerModelKill
	.globl __kerjmp_BoardBowserSuitMotionSetWait
__kerjmp_BoardBowserSuitMotionSetWait:
	b _BoardBowserSuitMotionSetWait
	.globl __kerjmp_BoardBowserSuitMotionSetWalk
__kerjmp_BoardBowserSuitMotionSetWalk:
	b _BoardBowserSuitMotionSetWalk
	.globl __kerjmp_BoardBowserSuitMotionSetWin
__kerjmp_BoardBowserSuitMotionSetWin:
	b _BoardBowserSuitMotionSetWin
	.globl __kerjmp_BoardBowserSuitMotionSetJump
__kerjmp_BoardBowserSuitMotionSetJump:
	b _BoardBowserSuitMotionSetJump
	.globl __kerjmp_BoardJunctionMaskSet
__kerjmp_BoardJunctionMaskSet:
	b _BoardJunctionMaskSet
	.globl __kerjmp_BoardJunctionMaskReset
__kerjmp_BoardJunctionMaskReset:
	b _BoardJunctionMaskReset
	.globl __kerjmp_BoardJunctionMaskZero
__kerjmp_BoardJunctionMaskZero:
	b _BoardJunctionMaskZero
	.globl __kerjmp_BoardPlayerResizeAnimExec
__kerjmp_BoardPlayerResizeAnimExec:
	b _BoardPlayerResizeAnimExec
	.globl __kerjmp_BoardWinCreate
__kerjmp_BoardWinCreate:
	b _BoardWinCreate
	.globl __kerjmp_BoardWinCreateChoice
__kerjmp_BoardWinCreateChoice:
	b _BoardWinCreateChoice
	.globl __kerjmp_BoardWinChoiceGet
__kerjmp_BoardWinChoiceGet:
	b _BoardWinChoiceGet
	.globl __kerjmp_BoardWinWait
__kerjmp_BoardWinWait:
	b _BoardWinWait
	.globl __kerjmp_BoardWinKill
__kerjmp_BoardWinKill:
	b _BoardWinKill
	.globl __kerjmp_BoardWinInit
__kerjmp_BoardWinInit:
	b _BoardWinInit
	.globl __kerjmp_BoardWinKillAll
__kerjmp_BoardWinKillAll:
	b _BoardWinKillAll
	.globl __kerjmp_BoardWinUnusedArraySet
__kerjmp_BoardWinUnusedArraySet:
	b _BoardWinUnusedArraySet
	.globl __kerjmp_BoardWinPause
__kerjmp_BoardWinPause:
	b _BoardWinPause
	.globl __kerjmp_BoardWinInsertMesSet
__kerjmp_BoardWinInsertMesSet:
	b _BoardWinInsertMesSet
	.globl __kerjmp_BoardWinAttrSet
__kerjmp_BoardWinAttrSet:
	b _BoardWinAttrSet
	.globl __kerjmp_BoardWinAttrReset
__kerjmp_BoardWinAttrReset:
	b _BoardWinAttrReset
	.globl __kerjmp_BoardWinChoiceDisable
__kerjmp_BoardWinChoiceDisable:
	b _BoardWinChoiceDisable
	.globl __kerjmp_BoardWinKeyWait
__kerjmp_BoardWinKeyWait:
	b _BoardWinKeyWait
	.globl __kerjmp_BoardWinSpeedGet
__kerjmp_BoardWinSpeedGet:
	b _BoardWinSpeedGet
	.globl __kerjmp_BoardWinSpeedSet
__kerjmp_BoardWinSpeedSet:
	b _BoardWinSpeedSet
	.globl __kerjmp_BoardWinPriSet
__kerjmp_BoardWinPriSet:
	b _BoardWinPriSet
	.globl __kerjmp_BoardWinChoiceNowGet
__kerjmp_BoardWinChoiceNowGet:
	b _BoardWinChoiceNowGet
	.globl __kerjmp_BoardWinChoiceNowGet2
__kerjmp_BoardWinChoiceNowGet2:
	b _BoardWinChoiceNowGet2
	.globl __kerjmp_BoardStatusCreate
__kerjmp_BoardStatusCreate:
	b _BoardStatusCreate
	.globl __kerjmp_BoardStatusKill
__kerjmp_BoardStatusKill:
	b _BoardStatusKill
	.globl __kerjmp_BoardStatusVisibleGet
__kerjmp_BoardStatusVisibleGet:
	b _BoardStatusVisibleGet
	.globl __kerjmp_BoardStatusShowSet
__kerjmp_BoardStatusShowSet:
	b _BoardStatusShowSet
	.globl __kerjmp_BoardStatusShowSetForce
__kerjmp_BoardStatusShowSetForce:
	b _BoardStatusShowSetForce
	.globl __kerjmp_BoardStatusGraySet
__kerjmp_BoardStatusGraySet:
	b _BoardStatusGraySet
	.globl __kerjmp_BoardStatusShowSetAll
__kerjmp_BoardStatusShowSetAll:
	b _BoardStatusShowSetAll
	.globl __kerjmp_BoardStatusStopCheck
__kerjmp_BoardStatusStopCheck:
	b _BoardStatusStopCheck
	.globl __kerjmp_BoardSpriteCreate
__kerjmp_BoardSpriteCreate:
	b _BoardSpriteCreate
	.globl __kerjmp_BoardStatusTargetPosSet
__kerjmp_BoardStatusTargetPosSet:
	b _BoardStatusTargetPosSet
	.globl __kerjmp_BoardStatusPosSet
__kerjmp_BoardStatusPosSet:
	b _BoardStatusPosSet
	.globl __kerjmp_BoardStatusPosGet
__kerjmp_BoardStatusPosGet:
	b _BoardStatusPosGet
	.globl __kerjmp_BoardStatusItemHideSet
__kerjmp_BoardStatusItemHideSet:
	b _BoardStatusItemHideSet
	.globl __kerjmp_BoardStatusHammerCreate
__kerjmp_BoardStatusHammerCreate:
	b _BoardStatusHammerCreate
	.globl __kerjmp_BoardStatusHammerKill
__kerjmp_BoardStatusHammerKill:
	b _BoardStatusHammerKill
	.globl __kerjmp_BoardStatusHammerShowSet
__kerjmp_BoardStatusHammerShowSet:
	b _BoardStatusHammerShowSet
	.globl __kerjmp_BoardPickerCreate
__kerjmp_BoardPickerCreate:
	b _BoardPickerCreate
	.globl __kerjmp_BoardPickerDoneCheck
__kerjmp_BoardPickerDoneCheck:
	b _BoardPickerDoneCheck
	.globl __kerjmp_BoardPickerChoiceGet
__kerjmp_BoardPickerChoiceGet:
	b _BoardPickerChoiceGet
	.globl __kerjmp_BoardPickerPosGet
__kerjmp_BoardPickerPosGet:
	b _BoardPickerPosGet
	.globl __kerjmp_BoardPickerBackFlagSet
__kerjmp_BoardPickerBackFlagSet:
	b _BoardPickerBackFlagSet
	.globl __kerjmp_BoardItemGetDestPos
__kerjmp_BoardItemGetDestPos:
	b _BoardItemGetDestPos
	.globl __kerjmp_BoardItemUseExec
__kerjmp_BoardItemUseExec:
	b _BoardItemUseExec
	.globl __kerjmp_BoardItemStatusKill
__kerjmp_BoardItemStatusKill:
	b _BoardItemStatusKill
	.globl __kerjmp_BoardYourTurnExec
__kerjmp_BoardYourTurnExec:
	b _BoardYourTurnExec
	.globl __kerjmp_BoardMusStart
__kerjmp_BoardMusStart:
	b _BoardMusStart
	.globl __kerjmp_BoardAudSeqFadeOutFast
__kerjmp_BoardAudSeqFadeOutFast:
	b _BoardAudSeqFadeOutFast
	.globl __kerjmp_BoardAudSeqFadeOut
__kerjmp_BoardAudSeqFadeOut:
	b _BoardAudSeqFadeOut
	.globl __kerjmp_BoardMusLoudSet
__kerjmp_BoardMusLoudSet:
	b _BoardMusLoudSet
	.globl __kerjmp_BoardMusVolPanSet
__kerjmp_BoardMusVolPanSet:
	b _BoardMusVolPanSet
	.globl __kerjmp_BoardAudSeqPause
__kerjmp_BoardAudSeqPause:
	b _BoardAudSeqPause
	.globl __kerjmp_BoardMusStatusGet
__kerjmp_BoardMusStatusGet:
	b _BoardMusStatusGet
	.globl __kerjmp_BoardAudSeqFadeOutAll
__kerjmp_BoardAudSeqFadeOutAll:
	b _BoardAudSeqFadeOutAll
	.globl __kerjmp_BoardAudFXPlay
__kerjmp_BoardAudFXPlay:
	b _BoardAudFXPlay
	.globl __kerjmp_BoardAudFXStop
__kerjmp_BoardAudFXStop:
	b _BoardAudFXStop
	.globl __kerjmp_BoardComKeySetLeft
__kerjmp_BoardComKeySetLeft:
	b _BoardComKeySetLeft
	.globl __kerjmp_BoardComKeySetUp
__kerjmp_BoardComKeySetUp:
	b _BoardComKeySetUp
	.globl __kerjmp_BoardComKeySetRight
__kerjmp_BoardComKeySetRight:
	b _BoardComKeySetRight
	.globl __kerjmp_BoardComKeySetDown
__kerjmp_BoardComKeySetDown:
	b _BoardComKeySetDown
	.globl __kerjmp_BoardComPreferItemCheck
__kerjmp_BoardComPreferItemCheck:
	b _BoardComPreferItemCheck
	.globl __kerjmp_BoardComPreferItemGet
__kerjmp_BoardComPreferItemGet:
	b _BoardComPreferItemGet
	.globl __kerjmp_BoardComFarPlayerFind
__kerjmp_BoardComFarPlayerFind:
	b _BoardComFarPlayerFind
	.globl __kerjmp_boardTutorialData
__kerjmp_boardTutorialData:
	b _boardTutorialData
	.globl __kerjmp_BoardTutorialHookSet
__kerjmp_BoardTutorialHookSet:
	b _BoardTutorialHookSet
	.globl __kerjmp_BoardRollTutorialSet
__kerjmp_BoardRollTutorialSet:
	b _BoardRollTutorialSet
	.globl __kerjmp_BoardTutorialDirInputSet
__kerjmp_BoardTutorialDirInputSet:
	b _BoardTutorialDirInputSet
	.globl __kerjmp_BoardCharWheelTargetSet
__kerjmp_BoardCharWheelTargetSet:
	b _BoardCharWheelTargetSet
	.globl __kerjmp_BoardTutorialBlockSetPos
__kerjmp_BoardTutorialBlockSetPos:
	b _BoardTutorialBlockSetPos
	.globl __kerjmp_BoardTutorialItemSet
__kerjmp_BoardTutorialItemSet:
	b _BoardTutorialItemSet
	.globl __kerjmp_BoardTutorialHostSet
__kerjmp_BoardTutorialHostSet:
	b _BoardTutorialHostSet
	.globl __kerjmp_BoardMGSetupTutorialExec
__kerjmp_BoardMGSetupTutorialExec:
	b _BoardMGSetupTutorialExec
	.globl __kerjmp_BoardShopTutorialExec
__kerjmp_BoardShopTutorialExec:
	b _BoardShopTutorialExec
	.globl __kerjmp_BoardLotteryTutorialExec
__kerjmp_BoardLotteryTutorialExec:
	b _BoardLotteryTutorialExec
	.globl __kerjmp_BoardBooHouseTutorialExec
__kerjmp_BoardBooHouseTutorialExec:
	b _BoardBooHouseTutorialExec
