/* GENERATED by port/tools/gen_stubs.py -- do not edit.
 * One loud stub per SDK symbol the game calls that the port has not
 * implemented yet.  25 with a real signature from the SDK headers,
 * 1 without.
 */
#include "port.h"
#include <dolphin.h>
#include <dolphin/gx.h>
#include <dolphin/card.h>
#include <dolphin/ai.h>
#include <dolphin/ar.h>
#include <dolphin/arq.h>
#include <dolphin/dsp.h>
#include <dolphin/thp.h>
#include <dolphin/demo/DEMOStats.h>
#include <stddef.h>

u32 ARAlloc(u32 length) {
    port_stub("ARAlloc");
    return (u32)0;
}
u32 ARFree(u32* length) {
    port_stub("ARFree");
    return (u32)0;
}
void C_QUATInverse(const Quaternion* src, Quaternion* inv) {
    port_stub("C_QUATInverse");
}
void C_QUATMultiply(const Quaternion* p, const Quaternion* q, Quaternion* pq) {
    port_stub("C_QUATMultiply");
}
void C_QUATNormalize(const Quaternion* src, Quaternion* unit) {
    port_stub("C_QUATNormalize");
}
void GXProject(f32 x, f32 y, f32 z, const f32 mtx[3][4], const f32 *pm, const f32 *vp, f32 *sx, f32 *sy, f32 *sz) {
    port_stub("GXProject");
}
void GXSetLineWidth(u8 width, GXTexOffset texOffsets) {
    port_stub("GXSetLineWidth");
}
void GXSetZTexture(GXZTexOp op, GXTexFmt fmt, u32 bias) {
    port_stub("GXSetZTexture");
}
void PSMTXMultVecSR(const Mtx m, const Vec* src, Vec* dst) {
    port_stub("PSMTXMultVecSR");
}
void PSMTXQuat(Mtx m, const Quaternion* q) {
    port_stub("PSMTXQuat");
}
void PSMTXTranspose(const Mtx src, Mtx xPose) {
    port_stub("PSMTXTranspose");
}
void PSQUATAdd(const Quaternion* p, const Quaternion* q, Quaternion* r) {
    port_stub("PSQUATAdd");
}
void PSQUATInverse(const Quaternion* src, Quaternion* inv) {
    port_stub("PSQUATInverse");
}
void PSQUATMultiply(const Quaternion* p, const Quaternion* q, Quaternion* pq) {
    port_stub("PSQUATMultiply");
}
void PSQUATNormalize(const Quaternion* src, Quaternion* unit) {
    port_stub("PSQUATNormalize");
}
void PSVECAdd(const Vec* a, const Vec* b, Vec* ab) {
    port_stub("PSVECAdd");
}
f32 PSVECDistance(const Vec* a, const Vec* b) {
    port_stub("PSVECDistance");
    return (f32)0.0f;
}
f32 PSVECDotProduct(const Vec* a, const Vec* b) {
    port_stub("PSVECDotProduct");
    return (f32)0.0f;
}
f32 PSVECMag(const Vec* v) {
    port_stub("PSVECMag");
    return (f32)0.0f;
}
void PSVECScale(const Vec* src, Vec* dst, f32 scale) {
    port_stub("PSVECScale");
}
f32 PSVECSquareDistance(const Vec* a, const Vec* b) {
    port_stub("PSVECSquareDistance");
    return (f32)0.0f;
}
void PSVECSubtract(const Vec* a, const Vec* b, Vec* a_b) {
    port_stub("PSVECSubtract");
}
u32 THPAudioDecode(s16* audioBuffer, u8* audioFrame, s32 flag) {
    port_stub("THPAudioDecode");
    return (u32)0;
}
BOOL THPInit(void) {
    port_stub("THPInit");
    return (BOOL)0;
}
s32 THPVideoDecode(void* file, void* tileY, void* tileU, void* tileV, void* work) {
    port_stub("THPVideoDecode");
    return (s32)0;
}
