/* GENERATED by port/tools/gen_stubs.py -- do not edit.
 * 0 SDK symbols with no prototype anywhere in the headers.  Declared
 * with no parameters and compiled without the SDK headers, so there is
 * nothing to disagree with: the caller passes its arguments in registers
 * and the stub ignores them, which is safe on both ABIs.
 */
#include "port.h"

