/* GENERATED by port/tools/gen_stubs.py -- do not edit.
 * One loud stub per SDK symbol the game calls that the port has not
 * implemented yet.  3 with a real signature from the SDK headers,
 * 0 without.
 */
#include "port.h"
#include <dolphin.h>
#include <dolphin/gx.h>
#include <dolphin/card.h>
#include <dolphin/ai.h>
#include <dolphin/ar.h>
#include <dolphin/arq.h>
#include <dolphin/dsp.h>
#include <dolphin/thp.h>
#include <dolphin/demo/DEMOStats.h>
#include <stddef.h>

u32 ARAlloc(u32 length) {
    port_stub("ARAlloc");
    return (u32)0;
}
u32 ARFree(u32* length) {
    port_stub("ARFree");
    return (u32)0;
}
void GXSetZTexture(GXZTexOp op, GXTexFmt fmt, u32 bias) {
    port_stub("GXSetZTexture");
}
